### ISSUE TITLE
Is there support for slot filling?

### ISSUE THREAD

**Issue by bluelight773** [golastmile/rasa_nlu#100]
Hi there

Is there support for slot filling where the user can provide all the necessary info for a given intent over multiple interactions 
Example:
User: I'm hungry
Bot: What kind of food would you like to eat?
User: Mexican
Bot: Are you looking to order delivery or go out?
User: Delivery
Bot: Here are some nearby options for Mexican food for delivery: ...

Or for a simpler more classic example - think booking an appointment where you're asked to provide time and with whom for instance.

Is there already support for this type of scenario? If so, could you point me to key parts of code/tutorial of relevance?  If not, is this on the roadmap, and is there some workaround way to do this in the meantime?

Thank you

**Comment by amn41** [comment]
Hi there,

thanks for this. This is outwith the scope of rasa NLU, so you will have to write a loop in your bot's code. There are a number of frameworks (e.g. botkit) which you can use to build your application logic.
