### ISSUE TITLE
MITIE install fails on Windows 10

### ISSUE THREAD

**Issue by maxiz** [golastmile/rasa_nlu#101]
Hi,

I'm trying to install MITIE backend on windows 10 using `pip install git+https://github.com/mit-nlp/MITIE.git`. However the install fails at the build step with the following error message.
`Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\njones\appdata\local\temp\pip-97mlgx-build
Installing collected packages: mitie
  Running setup.py install for mitie: started
    Running setup.py install for mitie: finished with status 'error'
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\njones\\appdata\\local\\temp\\pip-97mlgx-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\njones\appdata\local\temp\pip-ydwrn7-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\njones\\appdata\\local\\temp\\pip-97mlgx-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\njones\appdata\local\temp\pip-ydwrn7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\njones\appdata\local\temp\pip-97mlgx-build\`

Any suggestions on I could be doing wrong would be really helpful!

Thanks

**Comment by amn41** [comment]
Hi, This looks like a MITIE-specific issue rather than a rasa one. I would recommend opening an issue at https://github.com/mit-nlp/MITIE
