### ISSUE TITLE
Deprecating visualizer

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#108]
The visualizer was intended as a placeholder until we had a proper GUI for creating training data. Thanks to @azazdeaz we now have one, which you can check out [here](https://azazdeaz.github.io/rasa-nlu-trainer/). 

With version 0.6 we will remove the visualizer, in favour of using this GUI directly. There will be a separate tool for converting wit/LUIS/api exports to the rasa NLU format, so you'll use it like: 

```bash
python -m rasa_nlu.convert -d wit_download.json -o rasa_data.json
```

Where the `rasa_data.json` will be ready to upload to the web app. 

Questions / comments / concerns welcome!

**Comment by pilot** [comment]
👍

**Comment by amn41** [comment]
PR is #122
