### ISSUE TITLE
Issue with entity predicitons using spacy/sci-kit on Windows

### ISSUE THREAD

**Issue by StevieZissou** [golastmile/rasa_nlu#114]
Hi , I installed everything on W10 x64 python 2.7 - installed 
pip install -U spacy
python -m spacy.en.download all - 
conda install scikit-learn

I installed and followed restaurant example directly using luis json file, however when I run from cmd as below on trained model I receive incorrect values for predictions on entities however intent classification looks ok. I did not receive any errors on training only warning about using luis schema. Is there any indication if which components I should be looking at to resolve the issue (e.g. spacy version etc. ).
I also tested on larger training set and still the same. Any help really appreciated :) apologies if not the sort of thing that should be posted on issue board. 

Also is there a recommended uninstall method to upgrade to new versions ?

example output:
curl "http://localhost:5000/parse?q=I%20want%20some%20italian%20food"
{"text": "I want some italian food", "intent": "restaurant_search", 
"entities":
 [{"start": 7, "end": 11, "value": "some", "entity": "location"}, 
{"start": 12, "end": 19, "value": "italian", "entity": "cuisine"}, 
{"start": 20, "end": 24, "value": "food", "entity": "cuisine"}]}
curl "http://localhost:5000/parse?q=I%20am%20looking%20for%20chinese%20food"
{"text": "I am looking for chinese food", "intent": "restaurant_search", 
"entities": [{"start": 5, "end": 12, "value": "looking", "entity": "location"}, 
{"start": 17, "end": 24, "value": "chinese", "entity": "cuisine"}, 
{"start": 25, "end": 29, "value": "food", "entity": "cuisine"}]}

**Comment by amn41** [comment]
Hi Stevie. The example is just to show how rasa NLU works. This is a toy example with too little training to give reliable performance. Don't worry about this there's no reason to think there's a problem with your installation. If you have issues with your own dataset then please let me know.

**Comment by StevieZissou** [comment]
Hi Alan, Thanks for getting back to me, I rebuilt Python environment and all is running ok now.
