### ISSUE TITLE
Word index entity extraction

### ISSUE THREAD

**Issue by claytantor** [golastmile/rasa_nlu#120]
It would be helpful to use word indexes instead on start and end indexes. This is because parser expectations are too strict when using indexes. Using a word index would give way more flexibility and be easier to model grammatically.

```
{
            "text": "central indian restaurant",
            "intent": "restaurant_search",
            "entities": [{
                "start": 0,
                "end": 7,
                "value": "central",
                "entity": "location"
            }, {
                "start": 8,
                "end": 14,
                "value": "indian",
                "entity": "cuisine"
            }]
        }
```

`curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{"q":"western ethiopian restaurant"}' "http://localhost:5010/parse"`

returns:

```
{
  "text": "western ethiopian restaurant",
  "confidence": 0.62923096948763158,
  "intent": "restaurant_search",
  "entities": []
}
```

wheras:

```
{
            "text": "central indian restaurant",
            "intent": "restaurant_search",
            "entities": [{
                "word": 0,
                "value": "central",
                "entity": "location"
            }, {
                "word": 1,
                "value": "indian",
                "entity": "cuisine"
            }]
        }
```

would return:

```
{
  "text": "western ethiopian restaurant",
  "confidence": 0.61303896430569549,
  "intent": "restaurant_search",
  "entities": [
    {
      "word": 0,
      "value": "western",
      "entity": "location"
    },
    {
      "word": 1,
      "value": "ethiopian",
      "entity": "cuisine"
    }
  ]
}
```

**Comment by amn41** [comment]
Hi. Thanks for creating an issue. Actually the reason we use character indexes is precisely because they are invariant across tokenizers. For example, some tokenizers will split contractions (`don't`, `let's`) and others won't. So token indexes can be off. What is your downstream use case where you say that you want greater flexibility and grammatical models? Are you thinking of ngrams specifically?

**Comment by claytantor** [comment]
Sorry for my confusion, but parser entities are not being returned in cases where the indexes start and end don't match, this is because the entity start position is off because a previous entity is larger than expected. 

example again:

in the model:

```
{
            "text": "central indian restaurant",
            "intent": "restaurant_search",
            "entities": [{
                "start": 0,
                "end": 7,
                "value": "central",
                "entity": "location"
            }, {
                "start": 8,
                "end": 14,
                "value": "indian",
                "entity": "cuisine"
            }]
        }
```

with the query:

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{"q":"western ethiopian restaurant"}' "http://localhost:5010/parse"

returns:

```
{
  "text": "western ethiopian restaurant",
  "confidence": 0.62923096948763158,
  "intent": "restaurant_search",
  "entities": []
}
```

shouldn't your implementation return:

```
{
  "text": "western ethiopian restaurant",
  "confidence": 0.61303896430569549,
  "intent": "restaurant_search",
  "entities": [
    {
      "start": 0,
      "end":7,
      "value": "western",
      "entity": "location"
    },
    {
      "start": 9,
      "end":18,
      "value": "ethiopian",
      "entity": "cuisine"
    }
  ]
}
```

and it seems to me that it would be better to allow the model to use the word index and for the result to return the start and end for extraction.

**Comment by amn41** [comment]
What do you mean by 'start and end don't match' ? 
From your example it looks like what's happening is that the model doesn't have enough training data to generalise to "western ethiopian restaurant". Remember rasa doesn't do regex/ pattern matching, so you need enough data that a statistical model can work this out for itself

**Comment by claytantor** [comment]
Ok. That wasnt clear to me but makes sense.

**Comment by timtutt** [comment]
Hi - Sorry to revive this issue, but @amn41 - can you provide a little more context around the "enough training data to generalize"? 

How many examples are "enough"? 
Should those examples include several different possible cuisine types? 
And if you have enough should we expect the model to generalize new cuisine types mentioned?

Some of these things are lacking in the documentation... I've been working on a model and have tried as little as 40 examples and as many as 200,000 examples, but can't seen to find the right sweet spot to get the model to correctly extract entities. 

Thanks in advance!

**Comment by wrathagom** [comment]
This doesn't belong here. This issue is about the start/end positions in the training data format not training data amounts.

Saw your Gitter comments and will try to reply, but please do create a new issue too.
