### ISSUE TITLE
Issue with Luis Intent detection

### ISSUE THREAD

**Issue by OmShrivastava** [golastmile/rasa_nlu#131]
Hi

I am using "emulate": "**luis**", in response always getting intent=inform 
**please provide solution for Luis as I want to use luis only** 

**Request** http://localhost:5000/parse?q=hi

**Responce**  {"query": "hi", "topScoringIntent": {"score": 0.899448027958612, **"intent": "inform"**}, "entities": [{"endIndex": null, "startIndex": null, "score": null, "type": "cuisine", "entity": "hi"}]}

but if I use **wit** then getting correct intent 

**Request** http://localhost:5000/parse?q=hi
**Responce**  [{"entities": {"cuisine": {"start": 0, "confidence": null, "end": 2, "type": "value", "value": "hi"}}, "confidence": 0.899448027958612, **"intent": "greet"**, "_text": "hi"}]

**Comment by amn41** [comment]
Could you please provide a minimal reproducible example? Either the zip of a model dir or the training data you used?

**Comment by OmShrivastava** [comment]
Hi

I trying with sample data downloaded  from https://azazdeaz.github.io/rasa-nlu-trainer/

I am using backend  **spacy_sklearn** 

**Train using**
python -m rasa_nlu.train -c config.json

 **config.json**
{  
  "backend": "spacy_sklearn",
  "path" : "./",
  "data" : "./data/testData.json",
  "server_model_dir" : "./model_20170202-173924",
  "port" : 5000,
  "mitie_file": null,
  "write" : "./log.json"
}

if I am using Wit it's detecting **"intent": "greet"** but in luis always  showing **"intent": "inform"**

**Comment by amn41** [comment]
Thanks! Can confirm this is a bug, and a very silly one. See #135
