### ISSUE TITLE
Fixes for NER training with spaCy

### ISSUE THREAD

**Issue by honnibal** [golastmile/rasa_nlu#136]
tl;dr: Consider removing `nlp.entity.end_training()` in spaCy NER training.

Details here: https://github.com/explosion/spaCy/issues/773

Have been working hard on the neural network model, to be launched with spaCy 2.0. This should give much improved performance for both NER and intent classification.

**Comment by amn41** [comment]
Thanks! will give this a try

**Comment by honnibal** [comment]
Relevant fix went up on Thinc master last night, and isn't up on PyPi yet.
