### ISSUE TITLE
How to create or where to find the metadata.json

### ISSUE THREAD

**Issue by alekaizer** [golastmile/rasa_nlu#138]
Hi guys,

It's written that the metadata.json is in the model dir, but I can't find it

is the metadata.json the training data or is a generated file(and how to generate it) ?

**Comment by nurulishlah** [comment]
Hi @alekaizer, have you found metadata.json file? I got the same issue with you.

**Comment by amn41** [comment]
It's generated for you when you train the model and it's saved. 
1. have you run `rasa_nlu.train` ?
2. if using the spacy backend, did you download the spacy data?

**Comment by alekaizer** [comment]
@nurulishlah yes, I've found it after generation as @amn41 said :)

**Comment by nurulishlah** [comment]
Thanks @amn41 and @alekaizer I finally got it :D
