### ISSUE TITLE
TypeError: object pickle not returning list

### ISSUE THREAD

**Issue by alekaizer** [golastmile/rasa_nlu#139]
Hi guys,

i'm trying to test rasa from Python, and I'm getting this error, don't know what i'm doing wrong

here is my metadata.json file

```
{
    "intent_classifier": "./model_20170206-173042/intent_classifier.pkl", 
    "entity_extractor": "./model_20170206-173042/ner", 
    "trained_at": "20170206-173042", 
    "training_data": "./model_20170206-173042/training_data.json", 
    "language_name": "en", 
    "feature_extractor": null, 
    "backend": "spacy_sklearn"
}
```

and here is my test.py file

    from rasa_nlu.interpreters.spacy_sklearn_interpreter import SpacySklearnInterpreter
    import json
    metadata = json.loads(open('./model_20170206-173042/metadata.json').read())
    interpreter = SpacySklearnInterpreter(**metadata)
    interpreter.parse("How do I pay")
    interpreter.parse("how can I track my order")

and here is the Traceback of the error

`Traceback (most recent call last):
  File "/Users/me/proj/raasa/test.py", line 4, in <module>
    interpreter = SpacySklearnInterpreter(**metadata)
  File "build/bdist.macosx-10.12-intel/egg/rasa_nlu/interpreters/spacy_sklearn_interpreter.py", line 15, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/ma/core.py", line 5518, in __setstate__
    ndarray.__setstate__(self, (shp, typ, isf, raw))

TypeError: object pickle not returning list
`

is there anything wrong with the metadata file or is the interpreter wrong

**Comment by amn41** [comment]
which version are you using? Could you please update to the latest and see if the problem persists? Do you have cloudpickle installed?

**Comment by alekaizer** [comment]
@amn41 thx for the reply
py 2.7.x (obviously :) )
rasa version: 0.4.2.1
cloudpicke installed

**Comment by amn41** [comment]
ok can you please upgrade to rasa 0.6 and try again?

**Comment by alekaizer** [comment]
yes, just did, issue still there

rasa 0.6.b0

cloudpickle is  up to date too

**Comment by amn41** [comment]
Do you still have this issue? closing for now but can reopen.

**Comment by ajayrfhp** [comment]
I have 2 system configurations and I get this error in one system configuration. The other configuration works fine for the same script. RASA_NLU version is 0.8.11 in both. I have cloud pickle installed in both with version 0.3.1. Any other things I could check ?

**Comment by tmbo** [comment]
@ajayrfhp what is the code you are using? Please describe in detail what you are doing

**Comment by ajayrfhp** [comment]
I was doing intent classification and have 2 system configurations. The code is described below. This throws the 'TypeError: object pickle not returning list' at interpreter.load. 

Is the error related, I think its a result of some other library update ( eg : pickle ), but I checked versions of pickle in both systems, they are same. 

Rasa_version = 0.8.11


`
training_data = load_data('frame_data.json')
trainer = Trainer(RasaNLUConfig("config.json"))
trainer.train(training_data)
model_directory = trainer.persist('./models/')

metadata = Metadata.load(model_directory)
interpreter = Interpreter.load(metadata, RasaNLUConfig("config.json"))
`
Config.json
`
"pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "amazon_character.json"
`
