### ISSUE TITLE
Multiple cores when training

### ISSUE THREAD

**Issue by azzuwan** [golastmile/rasa_nlu#141]
I know it is an inherent limitation of Python but is it possible to make the situation slightly better with the current setup? We have 32 cores machines on Digital Ocean that we are hoping to use for experimenting with Rasa NLU.

**Comment by tmbo** [comment]
@azzuwan which backend are you using, spacy or mitie?

**Comment by azzuwan** [comment]
@tmbo  Brilliant! That commit is candy to me. I'm using MITIE. Going to try ASAP. Thanks!
