### ISSUE TITLE
what happened to the visualizer ? 

### ISSUE THREAD

**Issue by Skyba** [golastmile/rasa_nlu#142]
I remember having used a excellent tool to visualize the data in rasa_nu format. Something happened, I can't find it any more ! Same for the page http://rasa-nlu.readthedocs.io/en/latest/visualize.html. 

That tool was really amazing, hope we can find it again soon =). Or at least, update the page http://rasa-nlu.readthedocs.io/en/latest/closeloop.html, where it is mentioned. Thank you!

**Comment by tmbo** [comment]
It got replaced by another (even cooler) project: https://github.com/azazdeaz/rasa-nlu-trainer

You can find an online version of it running here:
https://azazdeaz.github.io/rasa-nlu-trainer/

**Comment by amn41** [comment]
Thanks for also fixing the docs! Closing now

**Comment by Skyba** [comment]
Amazing. Thank you.
