### ISSUE TITLE
Support for Contexts - input context and output context

### ISSUE THREAD

**Issue by getramki** [golastmile/rasa_nlu#146]
Hi,
I am new to NLP, in the past few months I have tried api.ai and wit.ai for my app. They are really good but I don't want my business to depend on them, I was searching for a tool for the exact reasons mentioned by @amn41 in his fantastic blog and that is when I stumbled upon this awesome tool, I have been trying this RASA from past few days which sufficed most of my requirements, I want to go native way with RASA, as I am just starting up.
I just want to know, is there is way to put Input context and output contexts on the intents to build dialog.
Have I missed anything in the documentation or can this be an enhancement in future?

thanks
RamaKrishna

**Comment by amn41** [comment]
thanks! This is quite a commonly asked question, so I'll had it to the FAQ. Rasa NLU is designed to be stateless, so will not handle dialogue for you. If you want some hints on how to do that feel free to email me.
