### ISSUE TITLE
Tokenizer doesn't do steming

### ISSUE THREAD

**Issue by sjjpo2002** [golastmile/rasa_nlu#156]
I'm using mitie backend. I have an entry in my training data like this:

```
{
      "text" : "show me my high alarms.",
      "entities" : [
        {
          "entity" : "intent",
          "value" : "\"alarms.alarm.list\""
        },
        {
          "entity" : "alarm-type",
          "value" : "\"high alarm\"",
          "start" : 11,
          "end" : 21
        }
      ]
    },
```

when training this I get this warning and at the end training fails:

` UserWarning: token alarm does not appear in tokenized sentence [u'show', u'me', u'my', u'high', u'alarms', u'.'].Entities must span whole tokens.
`
looks like there is no stemming done before checking the entity values with what's in the utterance. Is this a bug or I'm missing something?

**Comment by amn41** [comment]
No you're quite right rasa doesn't do stemming, you can do this as a postprocessing step for now, we're working on something more robust. What exactly is your use case? Should `alarm` and `high alarm` be different entity types?
