### ISSUE TITLE
ImportError: No module named sklearn.model_selection

### ISSUE THREAD

**Issue by abubakarsohail** [golastmile/rasa_nlu#157]
I followed the steps in the documentation and installed spacy and sickit-learn(using conda). After setting up  the backend and trying to train. I get ImportError: No module named sklearn.model_selection. Please see the screenshot. 
![capture](https://cloud.githubusercontent.com/assets/20099503/22904223/7177be84-f25d-11e6-85fe-06d9986fc74d.PNG)

**Comment by tmbo** [comment]
Try to change the version of sklearn in 
https://github.com/golastmile/rasa_nlu/blob/master/conda-requirements.txt#L2
to `0.18.1` and update your conda, does that help?

**Comment by abubakarsohail** [comment]
Nope. Still the same error.

**Comment by amn41** [comment]
Are you still experiencing this error? Are you able to import this module in the repl? Maybe uninstall and reinstall

**Comment by abubakarsohail** [comment]
Nope. Well @amn41 let me tell you the whole story. I was trying to install MITIE on Windows 10 but it just won't install. It always gave me the error, "The file specified could not be found". So, I decided to try spacy. It installed successfully. But I wasn't able to use it (Refer to the first post in this thread for screenshot). After wasting 2 days on it, I decided to try linux since my friend told me that he was able to install MITIE successfully on linux. Everything went well on linux. I have setup MITIE on Ubuntu without any problems.

**Comment by amn41** [comment]
OK yes there's a known issue of MITIE on windows. No idea why sklearn wouldn't work though. Closing this.

**Comment by abubakarsohail** [comment]
@amn41 Please don't close the issue yet. Because I would be very much happy to have rasa working on Windows 10 since I am comfortable with working on Windows. Just tell me what I need to do to get rasa working on Windows 10 either with MITIE or spacy.

**Comment by tmbo** [comment]
@abubakarsohail judging by the error you posted it most likely is a version issue with sklearn.
When you execute smth like
`python -c "import sklearn; print sklearn.__version__"`
What version gets printed? If that is lower than 0.18, then that is the wrong version.

**Comment by abubakarsohail** [comment]
This is what I got @tmbo 
![capture](https://cloud.githubusercontent.com/assets/20099503/23042786/d808c93a-f4bb-11e6-91b4-9ee873076bd7.PNG)

**Comment by tmbo** [comment]
This seems like the python package is not installed at all. Which commands did you run to install the dependencies?

**Comment by abubakarsohail** [comment]
Please check the screenshot @tmbo. I guess everything looks fine from the installation point of view.
![capture](https://cloud.githubusercontent.com/assets/20099503/23043148/2afd92a0-f4bd-11e6-9884-6deeed0401fc.PNG)

**Comment by tmbo** [comment]
Yes that looks good. And the issue still persists?

**Comment by abubakarsohail** [comment]
I am afraid, it does. Please, have a look at the screenshot.
![capture](https://cloud.githubusercontent.com/assets/20099503/23043461/270dfe72-f4be-11e6-981e-f11b919031a1.PNG)

**Comment by tmbo** [comment]
Can you try installing `sklearn` with pip instead of anaconda, eg. `pip install sklearn`

**Comment by abubakarsohail** [comment]
It doesn't work either.
![capture](https://cloud.githubusercontent.com/assets/20099503/23043776/540cac9c-f4bf-11e6-8906-b9cea8052d3d.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/23043788/601dbe22-f4bf-11e6-99b3-899cb2b35fa9.PNG)

**Comment by tmbo** [comment]
Try installing all the dependencies using `pip install -r requirements.txt`

**Comment by abubakarsohail** [comment]
@tmbo Is this normal? Please, have a look.
![capture](https://cloud.githubusercontent.com/assets/20099503/23044109/9adbe808-f4c0-11e6-9bb9-78ee47ae0ed8.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/23044144/c5f04e80-f4c0-11e6-93d9-636a9853e84e.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/23044156/d862e92e-f4c0-11e6-8ef0-f8019bd2468d.PNG)

**Comment by abubakarsohail** [comment]
@tmbo Hey, I am still a newbie. So, can you tell me which one's better to use, MITIE or spacy? Also, did you see the screenshots?

**Comment by tmbo** [comment]
Since the installation error is mitie related you can try using spacy first to see if that is working.

**Comment by abubakarsohail** [comment]
Please, have a look at the screenshots @tmbo .
![capture](https://cloud.githubusercontent.com/assets/20099503/23073481/865a641c-f557-11e6-8bf6-db2cd39c6214.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/23073501/9dd1a1e6-f557-11e6-8a19-6091ea4e18f3.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/23073522/b147c412-f557-11e6-8ef1-e0c95172cac7.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/23073546/c4745776-f557-11e6-884d-4f697f1d46ea.PNG)

**Comment by abubakarsohail** [comment]
@tmbo @amn41 I did everything from the start. Installed everything from the start. But all in vain. Still stuck at the same position. Can you please help me set up spacy?
![capture](https://cloud.githubusercontent.com/assets/20099503/23085167/da7ab008-f587-11e6-976d-010dacb646ce.PNG)

**Comment by abubakarsohail** [comment]
Hey @amn41 , since someone else is having the same issue as mine. Can you please help me resolve the issue? I am having the exact same issue.

**Comment by amn41** [comment]
This seems to be an issue with installing sklearn on windows, and is unrelated to rasa. I would suggest you have a look at the github issues page for scikit-learn.

**Comment by lkluo** [comment]
Do you have two version python?

**Comment by avichauhan6832** [comment]
Hola there,
Sklearn is working there only in windows 10 where have the security of administration applied.
How to get it to work in other directories?

**Comment by UtpalBhadra93** [comment]
Pls check your file name.
Might be u r saving it with the same name as sklearn,
so everytime u run u will face the same prob.

Python search for the file first within ur directory and if it is not there then only it shifts to its own defined directory.

**Comment by mukund7296** [comment]
pip install -U scikit-learn scipy matplotlib


install this library

**Comment by babaralishah** [comment]
Hi All!
Getting this error since a week, please help...
from . import __check_build  # noqa: F401
ImportError: cannot import name '__check_build' from 'sklearn'
