### ISSUE TITLE
rasa-nlu-trainer

### ISSUE THREAD

**Issue by Tejaf** [golastmile/rasa_nlu#165]
Hello, I noticed that the former visualization software has been replaced with this super cool https://golastmile.github.io/rasa-nlu-trainer/. I'm having a situation here though, after installation and all, I can't seem to get it to use my example_data, instead it uses the default in `usr/local/lib/node_modules/rasa-nlu-trainer/src/testData.json`
How do I specify the data it should visualize please, I tried this `rasa-nlu-trainer --source /Users/macbookair/Documents/my_dockerbuilds/data/demo-rasa.json ` 

after reading this instruction

```$ rasa-nlu-trainer in your working directory

this will open the editor in your browser

options

--source -s path to the training file (by default it will be searched recursively in the current directory)
--port -p the web app will run here (randomly selected by default)```


thanks

**Comment by amn41** [comment]
If you just want to use the tool, you can just go to https://golastmile.github.io/rasa-nlu-trainer/

then use the buttons in the top right to load your file :)

**Comment by Tejaf** [comment]
Hi Alan,
I tried it, it says `no data`

**Comment by amn41** [comment]
ah - you may have to modify your file to switch `"intent_examples"` to `"common_examples"`

**Comment by Tejaf** [comment]
Okay, how do I do that? change `intent_examples` to `common_examples`?

**Comment by Tejaf** [comment]
Ah! both works now `rasa-nlu-trainer --source /Users/macbookair/Documents/my_dockerbuilds/data/demo-rasa.json` and ` https://golastmile.github.io/rasa-nlu-trainer/` thanks.
It's safe to close this :)
