### ISSUE TITLE
Spacy Built-in entity types

### ISSUE THREAD

**Issue by AndriiKr** [golastmile/rasa_nlu#166]
Hi,
Can we use Spacy Built-in entity types in rasa_nlu? https://spacy.io/docs/usage/entity-recognition#entity-types
Or we need to use them directly from Spacy?

**Comment by tmbo** [comment]
I just had a quick look at the code and I don't see a reason why it wouldn't use them. You need to use the specified entity names (e.g. `FACILITY`) and that should work.

Did you have any issues with that?

**Comment by tmbo** [comment]
I was actually wrong here, currently the models are not fine tuned. I created a PR to add the possibility to do that and hence reuse the pretrained entities from spacy.
