### ISSUE TITLE
false regex match in mitie tokenizer

### ISSUE THREAD

**Issue by dangerbahn** [golastmile/rasa_nlu#169]
attempt to train using this example:
```
{
  "rasa_nlu_data": {
    "common_examples": [{
      "text": "breathe the e cig",
      "intent": "example",
      "entities": [{
        "start": 12,
        "end": 17,
        "value": "e cig",
        "entity": "test"
      }]
    }]
  }
}
```
when training the model, an error is returned:

> ValueError: invalid entity {u'start': 12, u'end': 17, u'value': u'e cig', u'entity': u''} in example breathe the e cig: entities must span whole tokens

I believe the issue stems from a regular expression finding multiple matches on line 18 of src/tokenizers/mitie_tokenizer.py

```re.search(tok, _text[offset:])```

other examples that reproduce this issue:
"find d man brand shirts" 
"search h style hammocks"

(queries with words containing only one character are typically prime offenders)

**Comment by tmbo** [comment]
I think this is already fixed in the latest version of the code. I just tried your example with the latest master and the training worked without any issues. 

I'll close this, but feel free to comment if there is still an issue with the latest version.

**Comment by dangerbahn** [comment]
Ah, that's what I get for letting my working copy go stale! Thanks for the quick response, looks like the issue I was trying to describe has been fixed.
