### ISSUE TITLE
use unicode throughout

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#17]
I think we should read training data files in as unicode, and just represent all text with `unicode` objects and not `str`. 

In `training_data.py` I would propose we read the json files like this
```python
import codecs
f = codecs.open('data.json', encoding='utf-8')
data = json.loads(f.read())
```

then we should only have unicode objects everywhere and we can avoid using any str at all. NB this may have downstream effects in e.g. spacy_tokenizer.py so we should run all the tests to check everything still works.

**Comment by plauto** [comment]
Ok, I used as reference the pre-existing code, but this unicode thing you are proposing can be done...moreover, it will make the code much cleaner.

I will investigate the impact of this, and push it on a separate branch, once done!
