### ISSUE TITLE
nearest text example for given intent

### ISSUE THREAD

**Issue by vinnitu** [golastmile/rasa_nlu#170]
How can we get nearest text example for given intent?

![to do custom respose like api.ai small talk](http://i.piccy.info/i9/94c57af065db2b612526639229cceaf0/1487839266/45790/1121849/Screenshot_from_2017_02_23_10_38_13.png)

**Comment by amn41** [comment]
Could you please explain your question? I'm not sure what you're asking

**Comment by vinnitu** [comment]
for example I have such data.json

```
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "text1",
        "intent": "intent1",
        "entities": []
      },
      {
        "text": "text2",
        "intent": "intent1",
        "entities": []
      },
      {
        "text": "text3",
        "intent": "intent2",
        "entities": []
      },
      {
        "text": "text4",
        "intent": "intent2",
        "entities": []
      }
    ]
  }
}

```

and after prediction intent1 I need understand what of text1 or text2 more close to input text

**Comment by tmbo** [comment]
I think this is somewhat out of scope of the current framework. I am not sure how that would integrate with the current system, but let me know if you want to work on this and contribute it.
