### ISSUE TITLE
visualizer download button not downloading

### ISSUE THREAD

**Issue by Tejaf** [golastmile/rasa_nlu#174]
Hello, after adding my intents manually using https://golastmile.github.io/rasa-nlu-trainer/, I clicked on the download button to get the json format but the page just disappears and appear with nothing downloaded in my browser. What can I do? I don't want to loose all the datas I had already inputed.

**Comment by azazdeaz** [comment]
I'm sorry but you can't get that data back :( :(
I opened an issue for this here: https://github.com/golastmile/rasa-nlu-trainer/issues/11
Please use Chrome until it gets fixed.

**Comment by Tejaf** [comment]
:( :( Ok, thanks.
