### ISSUE TITLE
WindowsError: exception: access violation reading 0x00000028

### ISSUE THREAD

**Issue by abubakarsohail** [golastmile/rasa_nlu#178]
While training a data of 26 samples, I am getting this error. 
![capture](https://cloud.githubusercontent.com/assets/20099503/23302530/ddae86fe-fab0-11e6-94e9-2d7df3696efc.PNG)
![1](https://cloud.githubusercontent.com/assets/20099503/23302532/e12879e8-fab0-11e6-81d5-b1a36a6b79a8.PNG)
![2](https://cloud.githubusercontent.com/assets/20099503/23302536/e4296f58-fab0-11e6-9612-9fc88d10ca7a.PNG)

**Comment by tmbo** [comment]
Which version of `mitie` are you using?

**Comment by abubakarsohail** [comment]
The latest one. Downloaded and built mitie about 3-4 hours ago.

**Comment by tmbo** [comment]
This is most likely due to the mitie file not beeing found. Make sure you've set `mitie_file` correctly.

**Comment by tmbo** [comment]
@abubakarsohail where you able to mitigate the issue?

**Comment by abubakarsohail** [comment]
Yes @tmbo. Forgot to update you. Sorry.

**Comment by tmbo** [comment]
@abubakarsohail anything to share for future reference?

**Comment by abubakarsohail** [comment]
I don't know what exactly solved the problem. But I reproduced the exact same data in a separate file, trained it and it worked.

**Comment by KoolCards** [comment]
I have the exact same problem with the access violation. @abubakarsohail any other advice for solving the problem

**Comment by KoolCards** [comment]
I tried using reproducing the data in another file but no luck

**Comment by abubakarsohail** [comment]
Tried updating MITIE to the latest version?

**Comment by tmbo** [comment]
Make sure you follow the installation instructions at https://github.com/mit-nlp/MITIE#compiling-mitie-as-a-shared-library

**Comment by KoolCards** [comment]
i followed the instructions and it now works but not sure what the error was caused by
