### ISSUE TITLE
Entity Only Training

### ISSUE THREAD

**Issue by wrathagom** [golastmile/rasa_nlu#181]
Sorry, maybe I am missing something, but your documentation states that the rasa_nlu_documentation contains 3 different examples: common training (intent + entity), intent training, and entity training. But under `entity_examples` all of the entity arrays are empty 

`{
        "text": "hey", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "howdy", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "hey there", 
        "intent": "greet", 
        "entities": []
      }`

except for these, which look like `common` examples:

`{
        "text": "i'm looking for a place in the north of town", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 31,
            "end": 36, 
            "value": "north", 
            "entity": "location"
          }
        ]
      }`

and then you have intent only examples

`{
        "text": "anywhere in the west", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "central indian restaurant", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "indeed", 
        "intent": "affirm"
      }`

I fail to see how any of these are just training the entities...

**Comment by tmbo** [comment]
Alright, let's try to improve the documentation then. It states 
```
In the rasa NLU data format, there are three lists of examples: common_examples, intent_examples, and entity_examples. The common_examples are used to train both the entity and the intent models. In many cases it’s fine to put all of your training examples in there. However, if you need lots and lots of examples to train a good entity recogniser, that can mess up your intent model because your classes are totally unbalanced. In that case it makes sense to split up these lists.
```

Can you explain what is left unclear?

**Comment by wrathagom** [comment]
How do I train entities only? if I need `Lots and lots of examples to train a good entity recognizer` what would that look like. In the docs/examples you show intent only training and intent + entity, but you never show entity only.

What are labels as entity examples are in fact entity + intent.

**Comment by tmbo** [comment]
@wrathagom Currently that is not possible. (You might put all your examples into the `entity_examples` section and leave the `intent_examples` section empty, but I am not sure what will happen if you try to train that).

I am currently working on a pipeline implementation that allows you to specify the different components separately, hence you would be able to skip the intent classification step entirely.

**Comment by tmbo** [comment]
Works in the pipeline implementation, returned intent will be `null`.
