### ISSUE TITLE
Set up mitie_sklearn on Windows

### ISSUE THREAD

**Issue by abubakarsohail** [golastmile/rasa_nlu#182]
How do I set up miti_sklearn backend on Windows 10?

**Comment by tmbo** [comment]
You need to setup both, `mitie` and the `spaCy + scikit-learn` dependencies described here https://rasa-nlu.readthedocs.io/en/latest/backends.html.

We should add that to the documentation.

**Comment by abubakarsohail** [comment]
I have tried setting up MITIE in virtual environment of Anaconda where spacy+scikit-learn is already set up but failed. Please check the screenshot.
![capture](https://cloud.githubusercontent.com/assets/20099503/23341833/d58858a8-fc70-11e6-914d-1f82afe1f8cb.PNG)

**Comment by Tejaf** [comment]
mitie can be a real pain on windows, I gave up a long time ago. so many dependencies are needed.

**Comment by tmbo** [comment]
@abubakarsohail I think you should talk to the guys from MITIE, they are probably able to help you with these setup issues as this is not related to rasa NLU. But if there is some helpful hint they provide, feel free to let me know or add it to the documentation yourself
