### ISSUE TITLE
Error while setting up mitie_sklearn backend

### ISSUE THREAD

**Issue by Tejaf** [golastmile/rasa_nlu#183]
this is the error
```/site-packages/rasa_nlu/train.py", line 34, in create_trainer
    raise NotImplementedError("other backend trainers not implemented yet")
NotImplementedError: other backend trainers not implemented yet
```

this is my config_mitie_sklearn.json file
```
{
  "backend": "mitie_sklearn",
  "mitie_file": "total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./demo-rasa.json"
} 
```

I have all the dependencies and I have been able to successfully trained the data using `mitie` and `sklearn` backend respectively.

**Comment by tmbo** [comment]
On which version of rasa NLU are you running? The `mitie_sklearn` backend is not part of the released pypi package yet. You need to use the current master.

**Comment by Tejaf** [comment]
I'm not sure how to confirm the version

$rasa_nlu --version

doesn't seems to work :( but I installed it using pip install `rasa_nlu`

should I clone the git repo instead to have access to this backend?

**Comment by tmbo** [comment]
To get the version you can use something like 

But in general, if you installed using pip, you can switch to the current master using the instructions here http://rasa-nlu.readthedocs.io/en/latest/backends.html#setting-up-rasa-nlu

We'll release this version soon to pypi as 0.7.0 but for hacking around feel free to try it out now.

**Comment by Tejaf** [comment]
Thanks Tom

**Comment by Tejaf** [comment]
switched, I used
`python -m rasa_nlu.train -c mitie_sklearn.json` it's still the same error!
`NotImplementedError`
then I cd into the src directory to locally run `python
mitie_sklearn_trainer.py -c mitie_sklearn.json`

now I have this error `ImportError: No module named progressbar`.
Thanks.
