### ISSUE TITLE
Training of wit.ai data is failing

### ISSUE THREAD

**Issue by mayankg53** [golastmile/rasa_nlu#188]
Hi,
I trained for two samples of wit.ai data, for one training is working fine and sample data looks like:
```
{
  "data": [
    {
      "text": "100",
      "entities": [
        {
          "entity": "intent",
          "value": "\"appreciation\""
        }
      ]
    },
    {
      "text": "Bonjour",
      "entities": [
        {
          "entity": "intent",
          "value": "\"greeting\""
        }
      ]
    }
  ]
}
```
But for the other sample which is almost equivalent to the "demo-flights.json" which is present in the rasa_nlu package its giving error : "ValueError: ('The number of classes ', 0, ' has to be greater than one; got 1')"
Other sample look like this:
```
{
  "data" : [
    {
      "text" : "i want to go from berlin to tokyo tomorrow",
      "entities" : [
        {
          "entity" : "location",
          "value" : "\"berlin\"",
          "role" : "from",
          "start" : 18,
          "end" : 24
        },
        {
          "entity" : "location",
          "value" : "\"tokyo\"",
          "role" : "to",
          "start" : 28,
          "end" : 33
        },
        {
          "entity" : "datetime",
          "value" : "\"2016-05-29T00:00:00.000-07:00\"",
          "start" : 34,
          "end" : 42
        }
      ]
    },
    {
      "text" : "i'm looking for a flight from london to amsterdam next monday",
      "entities" : [
        {
          "entity" : "location",
          "value" : "\"london\"",
          "role" : "from",
          "start" : 30,
          "end" : 36
        },
        {
          "entity" : "location",
          "value" : "\"amsterdam\"",
          "role" : "to",
          "start" : 40,
          "end" : 49
        },
        {
          "entity" : "datetime",
          "value" : "\"2016-05-30T00:00:00.000-07:00\"",
          "start" : 50,
          "end" : 61
        }
      ]
    }
  ]
}
```
As number of classes are more than 1 instead of that also its giving this error, can you please check why it isn't working for the data set given for wit.ai in rasa_nlu package itself??

Do I have to change some code to train on the second set of data??

Regards,
Mayank

**Comment by tmbo** [comment]
@mayankg53 which backend and version of rasa are you using? 

Did I understand you correctly, the training does not work with your second snippet which is the same as in the wit demo json?

**Comment by mayankg53** [comment]
Correct second snippet isn't working with the error mentioned, I am using "spacy_sklearn" as backend and tag for my code is 0.5-14-gf770497. I have fetched sometime before the master branch and didn't pull the changes after that, have this issue been resolved in any of your updates.

**Comment by mayankg53** [comment]
I have fetched the latest code and tried with both backend "spacy_sklearn" and "mitie", both are working for the first snippet data but not working on second snippet data.
For mitie backend the error is "raise Exception("Unable to create text_categorizer_trainer based on " + filename)" and for spacy_sklearn I have mentioned the error in the issue itself.
Can you please check and let me know .

**Comment by tmbo** [comment]
Training does work for me without issues for mitie with the following config
```

**Comment by tmbo** [comment]
Training works for me using mitie with the following configuration:
```
{
  "backend": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./data/examples/wit/demo-flights.json"
}
```
Is that different from yours?

**Comment by mayankg53** [comment]
Yes same config file I am using and running with the command python -m rasa_nlu.train -c config.json where config.json  has the content you mentioned but I am getting the error I mentioned above 
"raise Exception("Unable to create text_categorizer_trainer based on " + filename)
Exception: Unable to create text_categorizer_trainer based on rasa_nlu.train"

**Comment by mayankg53** [comment]
0.7.0a4

**Comment by mayankg53** [comment]
I think problem is with running of mitie backend, as I am following steps mentioned in http://rasa-nlu.readthedocs.io/en/latest/tutorial.html. Can you please brief me the stable version to run mitie and the steps for the same as spacy_sklearn backend is running fine for the first snippet but the mitie isn't working for any of the snippet and getting the error mentioned in the above comment.

**Comment by mayankg53** [comment]
I think there was problem with set up of mitie, so that problem is resolved but I have 2 questions:
1. Tokenizer wit.ai using is different from rasa, as its giving me error while training "Entities must span whole tokens." For eg. Headphone for 50$ is tokenize as {"Headphone", "for","50","$"} so wit.ai tag entity 50 as price but rasa training is giving error as "Token '50' does not appear in tokenized sentence" as it is tokenizing as {"Headphone", "for","50$"}, how to resolve this part?
2. For such data why can't we use "spacy_sklearn" as backend?

**Comment by tmbo** [comment]
1. This is something you need to fix by hand / automate specific to your use case.
2. Thanks, I fixed that issue with the training data. Currently there is no support for the roles from api.ai
3. What is the issue with the `spacy_sklearn` backend?

**Comment by mayankg53** [comment]
For the second point, then how will I come to know which is "to" loc and which is from "loc" ?
For the third point, spacy_sklearn is working fine with other data sets but with such snippet of wit.ai with roles its giving error  "ValueError: ('The number of classes ', 0, ' has to be greater than one; got 1')" ?? Can you run once demo-flights.json data for spacy_sklearn backend and check whether its working fine or not?

**Comment by tmbo** [comment]
Spacy needs at least 3 training instances per class. That is most likely the issue and related to #198 

One current solution could be to use different entities for the types of the locations. An alternative would be to create a PR and add this functionality to rasa NLU ;)

**Comment by mayankg53** [comment]
Spacy needs at least 3 training instances per class. This thing I know so I had added some more samples to the demo-flights.json and try to run that but actually it gave me the error "ValueError: ('The number of classes ', 0, ' has to be greater than one; got 1')". I am not understanding for such data having roles what rasa considered as a class, can you please tell me for the snippet with roles what is the class for that data?
Definitely I will try to work on the role functionality.

**Comment by tmbo** [comment]
Currently only the intent of a message is considered and trained on. Hence, if you want your data to be specified using the wit.ai format, you need intent examples which do look like this:
```json
{  
   "text":"i want to fly from london",
   "entities":[  
      {  
         "entity":"location",
         "value":"london",
         "role":"from",
         "start":29,
         "end":25
      },
      {  
         "entity":"intent",
         "value":"some-intent"
      }
   ]
}
```

**Comment by mayankg53** [comment]
Thanks a lot
