### ISSUE TITLE
Multiple of same entity in a query

### ISSUE THREAD

**Issue by mikkelam** [golastmile/rasa_nlu#191]
Hi i am in a situation where i am making a negotiation bot, as such a user might reply:
> 250k is too low, i want at least 270k.

Now, `250k` and `270k` are both prices, but how do i model this? I think that mitie does not allow this

**Comment by amn41** [comment]
MITIE doesn't necessarily prevent this. What happens when you train this model?

**Comment by mikkelam** [comment]
It stopped being an issued a couple days after my post. It works as intended now.
