### ISSUE TITLE
Mapping multi-word phrases to "value"

### ISSUE THREAD

**Issue by PrajnyaSatish** [golastmile/rasa_nlu#194]
Hi,
I'm trying to map multiple word synonyms to a single value. For example,
`{
     "text": "how to save images?", "intent": "explain", "entities": [ { "start": 7, "end": 18, "value": "saveImages", "entity": "entityName" } ] },`

The `entity` is detected correctly but the `value` is not what I expect --
`{u'text': u'how to save images?', u'confidence': 0.8476407032279926, u'intent': u'explain', u'entities': [{u'start': 7, u'end': 18, u'value': u'save images', u'entity': u'entityName'}]}
`
Does rasa support this capability of mapping "save images" to a single `value` "saveImages"? (I have trained a lot of samples. About 10 samples for each different "value" in the entity `entityName` but I still don't see any improvement).

**Comment by tmbo** [comment]
Value should be the text in the sentence whereas entity should be the type of the found sequence of words.

`value` represents the text found in the sentence. Why would you not want to receive the text from the sentence their?

**Comment by PrajnyaSatish** [comment]
When I used this feature in wit I used to map all synonyms to a particular
value like "save images", "saving procedure", "saving images".  I thought
that was the function of this feature.

**Comment by PrajnyaSatish** [comment]
Also your documentation does specify this ability of `value` mapping synonyms.

**Comment by amn41** [comment]
see #151 - this should work fine

**Comment by PrajnyaSatish** [comment]
Yes,  this is what I was looking for.  Thank you.
