### ISSUE TITLE
Multiple intents response

### ISSUE THREAD

**Issue by bkmeneguello** [golastmile/rasa_nlu#199]
Hi, I'm coming from LUIS and noticed that interpreters returns only the more likely intent, instead of return the full intent list with scores.
My AI uses, sometimes, this list to make decisions of ambiguities.
rasa_nlu.classifiers.sklearn_intent_classifier.SklearnIntentClassifier#predict_prob return the full list. It's possible to return this list instead?

**Comment by tmbo** [comment]
I think we can make that an option, do you mind sharing the LUIS format?

**Comment by BharatSimhaReddy17** [comment]
could you please help me with the format for multiple intents?

**Comment by tmbo** [comment]
I am not quite sure what you are referring to. Do you mean the implementation of returning a list of intents including probability instead of the most probable one?

**Comment by BharatSimhaReddy17** [comment]
yea, i mean the implementation of returning a list of intents including probability.

**Comment by tmbo** [comment]
What is the format LUIS is using for this?

**Comment by bkmeneguello** [comment]
This is an example

```json
{
    "query": "us$ 5000.00",
    "topScoringIntent": {
        "intent": "Money Answer",
        "score": 0.9999938
    },
    "intents": [
        {
            "intent": "Money Answer",
            "score": 0.9999938
        },
        {
            "intent": "Number Answer",
            "score": 0.04435608
        }
    ],
    "entities": [
        {
            "entity": "us $",
            "type": "currency",
            "startIndex": 0,
            "endIndex": 2,
            "score": 0.9984345
        },
        {
            "entity": "5000 . 00",
            "type": "number",
            "startIndex": 4,
            "endIndex": 10,
            "score": 0.9975406
        }
    ]
}
```

**Comment by tmbo** [comment]
Implemented on `pipeline` branch. Only works when sklearn intent classifier is used (mitie doesn't return the probabilities for all classes).
