### ISSUE TITLE
Unable to retrain model properly

### ISSUE THREAD

**Issue by sourjatilak** [golastmile/rasa_nlu#200]
I training my model using the following content in training file:

{ "rasa_nlu_data": { "intent_examples": [{ "text": "i would love to marry you", "intent": "bot_compliment_marry", "entities": [] },{ "text": "please marry me", "intent": "bot_compliment_marry", "entities": [] },{ "text": "will you marry me", "intent": "bot_compliment_marry", "entities": [] }]}}

After that, I used:  curl -XPOST localhost:5000/parse -d'{"q":"marry you"}'
Rasa was giving me wrong intent.

So I tried to retrain the model:

curl -XPOST localhost:5000/train -d'{ "rasa_nlu_data": { "intent_examples": [{ "text": "marry you ", "intent": "bot_compliment_marry" }]}}'

curl -XPOST localhost:5000/parse -d'{"q":"marry you"}'
<Still the same wrong intent was coming>

curl -XPOST localhost:5000/train -d'{ "rasa_nlu_data": { "intent_examples": [{ "text": "Are you married ", "intent": "bot_compliment_marry" }]}}'

curl -XPOST localhost:5000/parse -d'{"q":"married are you"}'
<Still the same wrong intent was coming>

curl -XPOST localhost:5000/train -d'{ "rasa_nlu_data": { "intent_examples": [{ "text": "I want to  marry you ", "intent": "bot_compliment_marry" }]}}'

curl -XPOST localhost:5000/parse -d'{"q":"I want to  marry you"}'
<Still the same wrong intent was coming>

Can you tell me how to retrain the model properly.

My configuration is

root:{
    "num_threads": 1, 
    "log_level": 20, 
    "language": "en", 
    "mitie_file": "./total_word_feature_extractor.dat", 
    "emulate": null, 
    "config": "./config_mitie.json", 
    "fine_tune_spacy_ner": false, 
    "write": "./rasa_nlu_log.json", 
    "token": null, 
    "server_model_dir": "./maindata/model_20170303-221907", 
    "path": "./maindata", 
    "log_file": null, 
    "data": "./1.json", 
    "port": 5000, 
    "backend": "mitie"
}

**Comment by tmbo** [comment]
Training the model using the server endpoint will not reload the model. Hence, if you don't restart in between your train and parse queries, you will always use the same model.

Is it correct, that there is only one intent type in your data? (`bot_compliment_marry `) What is the response to your curls?

**Comment by sourjatilak** [comment]
curl -XPOST localhost:5000/parse -d'{"q":"marry you"}'
{
  "confidence": 0.6347048745488278, 
  "entities": [], 
  "intent": "activate", 
  "text": "marry you"
}

Is there a way to reload the model without restarting?

**Comment by tmbo** [comment]
At the moment there is no way to reload. The issue why we have not done that (and might not in the future - still undecided) is multi-process support. It's easy to reload the models within one process but everything else will be harder without introducing further dependencies. If you got a good idea here, feel free to share it.

 I would be quite surprised if that would be the output using the training data you posted. Since `"activate"` is not part of the training data I think there is no way it could be predicted. Are you sure the posted training data is the data you are using?

**Comment by sourjatilak** [comment]
I have added other intents as well. When I was trying to train this, it was
not working.
Can you help me out how to train it the correct way.

**Comment by sourjatilak** [comment]
Can you tell me the way to reload the model.
Right now, I have trained it with a lot of json files.

curl localhost:5000/status
{
  "available_models": [
    "./maindata/model_20170303-221907", 
    "./maindata/model_20170303-222710", 
    "./maindata/model_20170303-222804", 
    "./maindata/model_20170303-235028", 
    "./maindata/model_20170306-161133", 
    "./maindata/model_20170306-161154", 
    "./maindata/model_20170306-161213", 
    "./maindata/model_20170306-161225", 
    "./maindata/model_20170306-161243", 
    "./maindata/model_20170306-161245", 
    "./maindata/model_20170306-161247", 
    "./maindata/model_20170306-161303", 
    "./maindata/model_20170306-161338", 
    "./maindata/model_20170306-161443", 
    "./maindata/model_20170306-161503", 
    "./maindata/model_20170306-161525", 
    "./maindata/model_20170306-161553", 
    "./maindata/model_20170306-164329", 
    "./maindata/model_20170306-164412", 
    "./maindata/model_20170306-164413", 
    "./maindata/model_20170306-174601", 
    "./maindata/model_20170306-174603", 
    "./maindata/model_20170306-174631", 
    "./maindata/model_20170306-174634", 
    "./maindata/model_20170306-174635", 
    "./maindata/model_20170306-174641", 
    "./maindata/model_20170306-174645", 
    "./maindata/model_20170306-174648", 
    "./maindata/model_20170306-174652", 
    "./maindata/model_20170306-174703", 
    "./maindata/model_20170306-174707", 
    "./maindata/model_20170306-174717", 
    "./maindata/model_20170306-182946", 
    "./maindata/model_20170306-182959", 
    "./maindata/model_20170306-183031", 
    "./maindata/model_20170306-183037", 
    "./maindata/model_20170306-183038", 
    "./maindata/model_20170306-183049", 
    "./maindata/model_20170306-183108", 
    "./maindata/model_20170306-183132", 
    "./maindata/model_20170306-183144", 
    "./maindata/model_20170306-183212", 
    "./maindata/model_20170306-183225", 
    "./maindata/model_20170306-183227", 
    "./maindata/model_20170306-183235", 
    "./maindata/model_20170306-183239", 
    "./maindata/model_20170306-183240", 
    "./maindata/model_20170306-183256", 
    "./maindata/model_20170306-183317", 
    "./maindata/model_20170306-183323", 
    "./maindata/model_20170306-183325", 
    "./maindata/model_20170306-183326", 
    "./maindata/model_20170306-183327", 
    "./maindata/model_20170306-183328", 
    "./maindata/model_20170306-183329", 
    "./maindata/model_20170306-183354", 
    "./maindata/model_20170306-194008"
  ], 
  "trainings_under_this_process": 0
}

How do I know which model to load again.
I killed the process and started it again.
The response is the same.

**Comment by tmbo** [comment]
the dates are encoding the training time, hence `./maindata/model_20170306-194008` is your last model. Instead of loading all models, you can also specify the model the server should be serving. Have a look at https://rasa-nlu.readthedocs.io/en/latest/http.html#running-the-server

With the `server_model_dirs` property, you can set your most recent model using 
```
--server_model_dirs=./models/model_YYYYMMDD-HHMMSS
```

**Comment by wrathagom** [comment]
But since you were posting single intent values to the /train endpoint most of those are probably worthless. POSTing to the train end point doesn't add it to the training model, it creates a new model, with whatever was in your POST payload.

You need to combine your original training data with the new ones you were trying to post. Re-train and re-start rasa.

**Comment by tmbo** [comment]
I'll close this for now, let me know if you have any further questions.
