### ISSUE TITLE
Override the default log file.

### ISSUE THREAD

**Issue by PrajnyaSatish** [golastmile/rasa_nlu#209]
rasa NLU version: 0.7.0a4

Used backend & plattform: `mitie` on `linux`

Issue:

I save this as my config file - 

`{
  "backend": "mitie",
  "path" : "./",
  "language": "en",
  "mitie_file" : "./data/total_word_feature_extractor.dat",
  "write" : "log_files/rasa_nlu_log.json"
}`

When I run the code, I expect that the log files are located in a json file named `rasa_nlu_log.json` in a directory named `log_files`. But I see that the files are named `rasa_nlu_log-(some number).json` ex: `rasa_nlu_log-6569.json` in `log_files`. And each time I start up the project a new file is created. I want to be able to write in the same file `rasa_nlu_log.json` upon restart. I am not able to override this convention even when i give other file names or save locations. Can you please suggest where I need to make the changes?

**Comment by tmbo** [comment]
I am not sure we can fix this. The issue is multiprocessing. When multiple processes, each process will have its own logger and hence needs its own file to log to. Because we don't know if we are the "only" process, we can not omit this, even if there is only one process running. 

Furthermore, I am no certain you would want this file to be overwritten, since it is the storage of any past query you will lose otherwise.

**Comment by tmbo** [comment]
How about the following solution:
- change the configuration to point to a directory instead of a file (avoids confusion that the file doesn't exist)
- add date-time to file name as well to get a proper sorting

Does that work for you @PrajnyaSatish

**Comment by PrajnyaSatish** [comment]
Well right now the files do exist in the directory (`log_files`) I mentioned.. The problem is, I run the server locally and I do not have a lot of space in the disk. So saving a new file with each process may lead to memory issues if I don't delete it manually.

**Comment by tmbo** [comment]
How about adding to possibility to set the directory I mentioned to `None` and hence disabling the logging completely?

**Comment by PrajnyaSatish** [comment]
I changed my config file:
`{
  "backend": "mitie",
  "path" : "./",
  "language": "en",
  "mitie_file" : "./data/total_word_feature_extractor.dat",
  "write" : ""
}
`
Sent an empty string instead.
![capture](https://cloud.githubusercontent.com/assets/19686544/23794725/9e8d92aa-05b7-11e7-9c6e-04cee4605c5c.PNG)


However, this error did lead me to this 
`self.logfile = config['write'].replace(".json", "-{}.json".format(os.getpid()))`
and i replaced it with:
`self.logfile = config['write']`
So now the name of the write file is not altered in a new process

**Comment by PrajnyaSatish** [comment]
My issue is solved now.

**Comment by tmbo** [comment]
I fixed this on master. The configuration key is now called `response_log` instead of `write` and should point to a directory. If the value is set to `null` in the configuration, no log files will be created.
