### ISSUE TITLE
config.json vs metadata.json

### ISSUE THREAD

**Issue by laurentmih** [golastmile/rasa_nlu#219]
**rasa NLU version:** `0.7.0a7`

**Backend:** `MITIE`

**OS:** `macOS Sierra (latest)`

**Observed behaviour:** When running the command to start the HTTP server, `python -m rasa_nlu.server -c config.json --server_model_dirs=./model_YYYYMMDD-HHMMSS`, rasa takes the configuration cue from `metadata.json` in the model directory, instead of the `config.json` file specified on the commandline.

**Steps to reproduce behaviour:**
I train my models on another box, which has more raw processing power, then download the model to my local workstation to do tests with the trained model. The configuration while training on the server is different than when I work locally. The result is as follows, for `metadata.json`:
```
{
    "trained_at": "20170317-034420", 
    "should_fine_tune_spacy_ner": false, 
    "intent_classifier": "intent_classifier.dat", 
    "training_data": "training_data.json", 
    "language_name": "en", 
    "entity_synonyms": null, 
    "entity_extractor": "entity_extractor.dat", 
    "rasa_nlu_version": "0.7.3", 
    "feature_extractor": "../../total_word_feature_extractor.dat", 
    "backend": "mitie"
}
```
However, back on my local machine, the location of `feature_extractor` is different. As specified in the `config.json` file (the same holds for the `training_data`/`data` config variable):
```
{
  "backend": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./models/model_20170317-034420/traindata.json"
}
```
This throws an error (`Exception: Unable to load total_word_feature_extractor detector from total_word_feature_extractor.dat`), unsurprisingly, because it is locally in a different location/under a different path, vs on the training server.

**Expected behaviour:** I would expect the explicitly specified `config.json` to take precedence over the `metadata.json` configuration variables.

Additionally, though only tangentially related to this issue, it could perhaps help if the `File not found` error could be more explicit than `Could not open file`. But that's a nice-to-have and tangential to the current issue.

I'm open to contributing a fix, but I first wanted to bring the issue to light with the project maintainers.

**Comment by tmbo** [comment]
This should be fixed on the `pipeline` branch. The file path isn't part of the metadata anymore, but replaced with the fingerprint of the `total_word_feature_extractor.dat` file.

The training data path is relative to the model directory. Since that is copied to the model directory, there shouldn't be an issue with that path.

**Comment by laurentmih** [comment]
Ah, that's great, thanks for coming back on it!

**Comment by akhilgentoo** [comment]
i didn't get you,

  File "/usr/local/lib/python2.7/dist-packages/mitie/mitie.py", line 830, in __init__
    raise Exception("Unable to load total_word_feature_extractor detector from " + filename)
Exception: Unable to load total_word_feature_extractor detector from ./data/total_word_feature_extractor.dat



This is my issue

**Comment by amn41** [comment]
@akhilgentoo where did you save this file? It's safer to give the full path: e.g. `/home/user/data/total_word_feature_extractor.dat`
