### ISSUE TITLE
Unable to run mitie_sklean

### ISSUE THREAD

**Issue by titashneogi** [golastmile/rasa_nlu#222]
rasa NLU version 0.7.3

Used backend `mitie_sklearn` & plattform ubuntu:

Issue:
I am able to run the trainer but when I run the server I get the error
_No module found with alias "default" _

Not sure whats going on here. Running with MITIE works fine, something I am missing in this one ?

Please help

**Comment by tmbo** [comment]
@titashneogi so you are able to successfully train a model using `mitie_sklearn` and you end up with a folder containing that model?

**Comment by titashneogi** [comment]
@tmbo Yes that is correct. I can train and create model but when I run the server I get an error.

**Comment by tmbo** [comment]
Do you mind sharing your configuration, please?

**Comment by titashneogi** [comment]
Sure. Please see below

`{
  "backend": "mitie_sklearn",
  "mitie_file": "./MITIE-models/english/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "testData.json",
"server_model_dir" : "./models/model_20170318-190322"
}

`

Thanks!

**Comment by tmbo** [comment]
This seems to be a configuration issue. The configuration value `server_model_dir` has been renamed in `0.7` (please have a look at https://github.com/golastmile/rasa_nlu/blob/master/CHANGELOG.rst#070---2017-03-10)
