### ISSUE TITLE
Set certain entity to be required

### ISSUE THREAD

**Issue by davidyapdy** [golastmile/rasa_nlu#224]
Was developing my app (python 3.5) and notice that rasa will still pass if the required entity is not found. 

```
suppose::

{
  "intent": "search_restaurant",
  "entities": {
    "cuisine" : "Mexican",
    "location" : "center"
  }
}


if get: without the location entities. set location = required and ask for more info
{
  "intent": "search_restaurant",
  "entities": {
    "cuisine" : "Mexican"
    "location": " "
  }
}

```

It would be nice to have if rasa can force entity to be required out of the box instead of coding it from scretch and save some memory.

**Comment by amn41** [comment]
Thanks for creating this issue. This is important functionality but is outside the scope of rasa NLU, see #193

**Comment by davidyapdy** [comment]
You mean to say that you're making another package that deals with dialogue?

**Comment by amn41** [comment]
Yes
