### ISSUE TITLE
Defining Synonyms. 

### ISSUE THREAD

**Issue by shivkanthb** [golastmile/rasa_nlu#231]
Rasa is incredible :) 
Im curious to know if there is a way to define synonyms (like how it is in WIT)?

**Comment by amn41** [comment]
Sure - if you define entities as having the same `value` they will be treated as synonyms. 
If you need something more sophisticated you can extend / replace the `entity_synonyms` component https://github.com/golastmile/rasa_nlu/blob/master/rasa_nlu/extractors/entity_synonyms.py

```json
      {
        "text": "in the center of town",
        "intent": "search",
        "entities": [
          {
            "start": 7,
            "end": 13,
            "value": "center",
            "entity": "center"
          }
        ]
      },
      {
        "text": "in the centre of town",
        "intent": "search",
        "entities": [
          {
            "start": 7,
            "end": 13,
            "value": "centre",
            "entity": "center"
          }
        ]
      }
```

**Comment by tmbo** [comment]
:+1: i've added an example to the documentation of the training data format for future reference.

**Comment by shivkanthb** [comment]
Thank you. That was good to know :). However I guess, if Im porting a wit app (that has a lot of synonyms) directly to rasa , Ill make sure I train them with more samples actually containing the synonyms.
