### ISSUE TITLE
Training entity performance 

### ISSUE THREAD

**Issue by goodrahstar** [golastmile/rasa_nlu#234]
rasa NLU version (Don't know? https://goo.gl/g9QQg2):
Version : 0.6

Used backend ( `spacy_sklearn`) & plattform (linux):

Issue:
I trained the model using 35 sentences with 2 intents and 3 entity classes.

Sample json:
{
        "text": "i want to purchase a Apple MacBook",
        "intent": "Shopping_tech",
        "entities": [
          {
            "start": 27,
            "end": 34,
            "value": "MacBook",
            "entity": "model"
          }
        ]
      },

But model is labeling all the words in the sentence in some classes.
Question : i want to purchase an Apple MacBook

And predition:
product = [u'i want', u'to', u'Apple', u'MacBook'], 
model = [u'purchase an']

Why it is labeling 'to' and 'i want' into entities ??

What i am doing wrong?

**Comment by tmbo** [comment]
@goodrahstar Do you mind updating to 7.x (e.g. using the latest version from pip?), so we can be sure this is still an issue with the latest version?

**Comment by goodrahstar** [comment]
Done with latest version 0.8 but having issues while importing the modules as :

from rasa_nlu.trainers.spacy_sklearn_trainer import SpacySklearnTrainer
from rasa_nlu.interpreters.spacy_sklearn_interpreter import SpacySklearnInterpreter

as mentioned in http://rasa-nlu.readthedocs.io/en/stable/python.html

I guess the namespace is changed now.

**Comment by tmbo** [comment]
Please use the LATEST documentation (instead of stable) for the code from master (http://rasa-nlu.readthedocs.io/en/latest/python.html).

**Comment by goodrahstar** [comment]
Thanks @tmbo . Latest version resolved the issue. 👍
