### ISSUE TITLE
 Can not train an intent classifier. Need at least 2 different classes.

### ISSUE THREAD

**Issue by ajayrfhp** [golastmile/rasa_nlu#235]
rasa NLU version : 0.71 

Used backend and  platform : spacy_sklearn, osx. 

Issue:
Unable to train model with custom data. Exception thrown : Can not train an intent classifier. Need at least 2 different classes. 
Entities are empty. 
Data can be found here.  
http://www.jsoneditoronline.org/?id=8626482ee7f065338f2656d40ab90c9a. 

Config.json : 
{
  "backend": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data.json"
}

**Comment by tmbo** [comment]
It seems like you do not intent to use the entity extraction, which is fine. Nevertheless, all you training examples are using the attribute `entity_examples` and hence they are not used for intent classification training (which results in the error message).

Renaming the `entity_examples` into `intent_examples` or `common_examples` will fix your issue (see https://rasa-nlu.readthedocs.io/en/stable/dataformat.html)
