### ISSUE TITLE
add error message when no logfile key is specified in config.json

### ISSUE THREAD

**Issue by plauto** [golastmile/rasa_nlu#24]
**Problem**
Two scenarios:
- no config file specified. Empty dict is used as default configuration;
- config file specified, but the dictionary holds no logfile key;

DataRouter() in server.py assigns self.logfile=config["logfile"] but get method fails.

**Possible Solution**
verify if key is present in config dict:
- trigger an error and exit;
- use default value.

**Comment by amn41** [comment]
I would propose we just default the logfile to `rasa_nlu_logs.json` (in working dir)

**Comment by plauto** [comment]
Sounds perfect to me
