### ISSUE TITLE
How can I train from latest model.

### ISSUE THREAD

**Issue by jcampbell05** [golastmile/rasa_nlu#257]
```
nlp = spacy.load("en")
    trainer = SpacySklearnTrainer('en')
    training_data = TrainingData('./data/concept.json', 'spacy_sklearn', nlp)
    trainer.train(training_data)
    trainer.persist('./models')

    metadata = Metadata.load("./models/*")
    interpreter = SpacySklearnInterpreter.load(metadata, nlp=nlp)
    print interpreter.parse("House")
```

Right now the Metdata isn't loading the latest model.

**Comment by tmbo** [comment]
@jcampbell05 as this is your second issue: There is a reason we have an issue template, please use it.

Which version of rasa nlu are you using?

**Comment by tmbo** [comment]
If this is code using the stable version, loading the metadata should point to the directory of the model, e.g. `Metadata.load("./models/model_20170404-084248")`.

**Comment by jcampbell05** [comment]
@tmbo I found a way to dynamically pick the latest folder for the model now :)
