### ISSUE TITLE
Modularize requirements (per component?)

### ISSUE THREAD

**Issue by tmbo** [golastmile/rasa_nlu#259]
We need to somehow modularize the requirements. I am not sure what the best solution here is but one idea would be:
- have the basic requirements we always need installed via requirements / setup.py
- at some abstraction level, add functionality (e.g. at the component level) to allow a component to request additional requirements. This could for example be a function `validate` on the component that makes sure all necessary optional packages are installed (e.g. `mitie` or `spacy`).

**Comment by rmharrison** [comment]
Recommendation: To ease onboarding, ideally the 'getting starting' example should not require additional dependencies. 

For more advanced tutorials, the steps to install any additional dependencies should be *clearly* stated; assuming the reader has no prior experience in python (e.g. may not know about `pip` or `virtualenv`, so link to supplemental documentation).

**Comment by tmbo** [comment]
Fixed + merged.
