### ISSUE TITLE
Extracting Number Entities

### ISSUE THREAD

**Issue by james-aiwip** [golastmile/rasa_nlu#261]
**rasa NLU version** (e.g. `0.7.3`):

0.7.3

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

spacy_sklearn

**Operating system** (windows, osx, ...):

osx

**Issue**:

Is it possible to extract number entities ?

**Comment by tmbo** [comment]
Sure thing, you can use the `fine_tune_spacy_ner ` setting to resuse existing spay entities. There is an entity for cardinals (https://spacy.io/docs/usage/entity-recognition#entity-types) which should capture numbers.

**Comment by james-aiwip** [comment]
@tmbo is there an example I can use for the API for this ?

**Comment by tmbo** [comment]
Before training your model you need to add this key to your configuration e.g.:
```json
{
  "backend": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/examples/rasa/demo-rasa.json",
  "fine_tune_spacy_ner": true
}
```

After training your model you can use the server to shoot queries at it. and it should return your custom entities as well as the pretrained spacy entities.
