### ISSUE TITLE
Option to append rasa Mitie model

### ISSUE THREAD

**Issue by PrashantKS** [golastmile/rasa_nlu#266]
**rasa NLU version** (e.g. `0.7.3`): 0.7.3

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): 'mitie'

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**: I have trained rasa, backend Mitie with 15 intents. Took me around 6-7 hours for the training completion (ran the training with 16 GB RAM system in Ubuntu). I have to add 2-3 additional intents. Is there a way to append to the existing model?

**Comment by tmbo** [comment]
@PrashantKS unfortunately, mitie doesn't allow to resume the training after it has finished. currently there is no other way than to retrain the model. Might be a good idea to try the `mitie_sklearn` backend, should be faster to train, you should evaluate though if there is a performance hit for your use case.

**Comment by PrashantKS** [comment]
Thank you tmbo ... I tried sklearn for training ... It's extremely fast compared to Mitie ... And during run time I am using Mitie ... Works well.
