### ISSUE TITLE
Getting confidence values greater than 1

### ISSUE THREAD

**Issue by shivkanthb** [golastmile/rasa_nlu#268]
**rasa NLU version** (e.g. `0.7.3`):
0.7.3

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie

**Operating system** (windows, osx, ...):
osx

**Issue**:
After training, for some queries I get a confidence score > 1.0
Is there a specific range the confidence scores can take?

**Comment by tmbo** [comment]
This is expected for the MITIE classifier. It returns `max(weights*x-b)` for the winning binary classifier of its multiclass binary classifier set.

**Comment by tmbo** [comment]
I've updated the documentation to include this.

**Comment by shivkanthb** [comment]
Cool thank you :)
