### ISSUE TITLE
WindowsError: exception: access violation reading 0x00000028 on python -m rasa_nlu.train -c config_mitie.json

### ISSUE THREAD

**Issue by HardikShah289** [golastmile/rasa_nlu#269]
**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (mitie):

**Operating system** (windows server 2012):

**Issue**:
Not able to train using below command. find output also..
`C:\rasa_nlu-master>python -m rasa_nlu.train -c config_mitie.json
Training to recognize 2 labels: 'location', 'cuisine'
Part I: train segmenter
words in dictionary: 200000
num features: 271
now do training
C:           20
epsilon:     0.01
num threads: 1
cache size:  5
max iterations: 2000
loss per missed segment:  3
C: 20   loss: 3         1
C: 35   loss: 3         1
C: 20   loss: 4.5       1
C: 5   loss: 3  1
C: 20   loss: 1.5       0.888889
C: 20   loss: 3.75      1
C: 21.5   loss: 3       1
C: 20   loss: 3.375     1
C: 18.5   loss: 3       1
C: 20   loss: 3.1875    1
C: 20   loss: 2.9       1
C: 20   loss: 2.9       1
C: 20   loss: 2.97801   1
best C: 20
best loss: 3
num feats in chunker model: 4095
train: precision, recall, f1-score: 1 1 1
Part I: elapsed time: 4 seconds.

Part II: train segment classifier
now do training
num training samples: 9
C: 200   f-score: 1
C: 400   f-score: 1
C: 300   f-score: 1
C: 100   f-score: 1
C: 0.01   f-score: 0.875
C: 600   f-score: 1
C: 1400   f-score: 1
C: 3000   f-score: 1
C: 5000   f-score: 1
C: 2550   f-score: 1
C: 1325   f-score: 1
C: 712.5   f-score: 1
C: 406.25   f-score: 1
C: 253.125   f-score: 1
C: 176.563   f-score: 1
C: 138.281   f-score: 1
C: 119.141   f-score: 1
C: 109.57   f-score: 1
C: 104.785   f-score: 1
C: 102.393   f-score: 1
C: 101.196   f-score: 1
C: 100.598   f-score: 1
C: 100.299   f-score: 1
best C: 100.598
test on train:
4 0
0 5

overall accuracy: 1
Part II: elapsed time: 13 seconds.
df.number_of_classes(): 2
Training to recognize 4 categories: 'greet', 'restaurant_search', 'affirm', 'goo
dbye'
Train classifier
extracting text features
now do training
num training samples: 51
C: 200   f-score: 0.84
C: 400   f-score: 0.84
C: 300   f-score: 0.84
C: 100   f-score: 0.84
C: 0.01   f-score: 0.74
C: 600   f-score: 0.84
C: 1400   f-score: 0.84
C: 3000   f-score: 0.84
C: 5000   f-score: 0.84
C: 2550   f-score: 0.84
C: 1325   f-score: 0.84
C: 712.5   f-score: 0.84
C: 406.25   f-score: 0.84
C: 253.125   f-score: 0.84
C: 176.563   f-score: 0.84
C: 138.281   f-score: 0.84
C: 119.141   f-score: 0.84
C: 109.57   f-score: 0.84
C: 104.785   f-score: 0.84
C: 102.393   f-score: 0.84
C: 101.196   f-score: 0.84
C: 100.598   f-score: 0.84
C: 100.299   f-score: 0.84
best C: 100.598
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\rasa_nlu-master\rasa_nlu\train.py", line 72, in <module>
    do_train(config)
  File "C:\rasa_nlu-master\rasa_nlu\train.py", line 63, in do_train
    persisted_path = trainer.persist(config['path'], persistor)
  File "rasa_nlu\model.py", line 200, in persist
    update = component.persist(dir_name)
  File "rasa_nlu\classifiers\mitie_intent_classifier.py", line 67, in persist
    self.clf.save_to_disk(classifier_file, pure_model=True)
  File "mitie.py", line 732, in save_to_disk
    if (_f.mitie_save_text_categorizer_pure_model(filename, self.__obj) != 0):
WindowsError: exception: access violation reading 0x00000028

C:\rasa_nlu-master>`

**Content of configuration file** (if used & relevant):
config_mitie.json
```
{
  "pipeline": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/examples/rasa/demo-rasa.json"
}


```

**Comment by tmbo** [comment]
Please file this as a bug report on the MITIE repository (https://github.com/mit-nlp/MITIE/issues) as this is nothing specific to rasa NLU.

**Comment by tmbo** [comment]
In the meantime you could try to use a different backend, e.g. `mitie_sklearn`.

**Comment by HardikShah289** [comment]
This is the reply, i received. please help..

People keep posting weird errors when using rasa nlu that only happen when using rasa nlu. So I'm doubtful this has anything to do with MITIE. Can you post a python script that reproduces this problem? One that doesn't involve rasa nlu.

**Comment by HardikShah289** [comment]
I have installed mitie. but still while running below script, it said mitie not found. so, I copied mitiblib folder from mitib to rasa_nlu_master folder and then run the script again. 

python -m rasa_nlu.train -c config_mitie.json

after that, it started train but end up with above issue error. Did my approach is correct to correct mitie issue?

**Comment by KoolCards** [comment]
bump i have the exact same issue

**Comment by KoolCards** [comment]
@HardikShah289 did u find the soln?

**Comment by HardikShah289** [comment]
@koolCards , I was able to solve this 0x00000028 error, but after that I stopped working on that. Will try to recall what I did. Sorry for not able to help you much.

**Comment by HardikShah289** [comment]
May be I have reinstalled rasa again and few other packages again. If MITIE not working, go with scipy. It should work. I have downloaded below things at that time. don't remember exact steps.. might help..
MITIE-models-v0.2.tar.bz2
MITIE-master.zip
en_core_web_sm-1.2.0.tar.gz
scipy-0.19.0-cp27-cp27m-win32.whl
numpy-1.12.1+mkl-cp27-cp27m-win32.whl

**Comment by KoolCards** [comment]
Ok. I was not able to figure out what the problem was with MITIE, but I tried use scipy, and it works a lot better. Thanks!
