### ISSUE TITLE
[question] wrong intent and entity detection

### ISSUE THREAD

**Issue by vibhutibindal** [golastmile/rasa_nlu#270]
**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```
i am using demo-rasa.json as training data and spacy_sklearn as the backend. if my query is "which is the best phone avaliable in the market" then it is giving me the result as :
`{'text': u'which is the best phone avaliable in the market', 'confidence': 0.64447036573192351,
 'intent': u'restaurant_search',
 'entities': [
{u'start': 13, u'end': 23, u'value': u'best phone', u'entity': u'cuisine'}, 
{u'start': 41, u'end': 47, u'value': u'market', u'entity': u'cuisine'}
]
}`
The training data does not contain anything related to this context so i was expecting it  to return empty entities and intent?

**Comment by tmbo** [comment]
Intent classification is a multiclass problem, hence it will always classify a message as one intent, even if the message is of an intent never seen before. The classifier doesn't know the answer "I don't know" (it tries to hint at us with the confidence, but it still will give us the most likely intent).

The data provided is just example data, there are way to few entity examples in there, hence the classifier here isn't very good and wrongly classifies your examples.

**Comment by vibhutibindal** [comment]
@tmbo  i completely agree with you .  Thank you so much for your feedback.The only one thing i am unable to understand that why it is giving so high confidence.As we are planning to consume rasa-nlu i
was expecting rasa to give in my opinion a relatively low confidence not as high as 0.6.

**Comment by tmbo** [comment]
How high the value is really depends on the model used and also how much the model was overfitted (i.e. how many times the model saw the training data and hence how much the model remembers the examples). In general I wouldn't put to much emphasis on the scores (yet?).

**Comment by vibhutibindal** [comment]
@tmbo  thank you so much for your answer but i am stuck on this problem of identifying wrong intent and entity  for  text not present in the same data .i am stuck on this problem .can u help me with this?

**Comment by tmbo** [comment]
There is an issue that is describing this feature #387. 

At the moment here is what you should do:
- make sure you have collected enough training data
- are you running in a special domain, e.g. are there words that are quite uncommon? if so try including the `intent_featurizer_ngrams`
- try to find examples that break your model - collect training data in that direction
