### ISSUE TITLE
Unable to load models with Multiple Intent Classifiers

### ISSUE THREAD

**Issue by sourjatilak** [golastmile/rasa_nlu#273]
**rasa NLU version** (e.g. `0.7.3`): 0.8.0a4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):  ["init_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms","intent_featurizer_mitie", "intent_classifier_keyword","intent_classifier_mitie","intent_classifier_sklearn"]

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:
when I am starting the rasa server, I am getting:

Error deserializing object of type unsigned long
   while deserializing object of type std::string
ERROR:root:Failed to load model 'model_20170411-115044'. Error: Unable to load text_categorizer detector from /root/testrasa/models/model_20170411-115044/intent_classifier.pkl

**Content of configuration file** (if used & relevant):
```json

{
  "pipeline":["init_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms","intent_featurizer_mitie", "intent_classifier_keyword","intent_classifier_mitie","intent_classifier_sklearn"],
  "mitie_file": "../rasa_nlu/data/total_word_feature_extractor.dat",
  "path" : "models",
  "data" : "./123.json",
  "num_threads":4,
  "logs":"logs",
  "port":5001,
  "server_model_dirs":{
      "default":"model_20170411-115044"
    }
}

```

**Comment by tmbo** [comment]
mhm, this is due to the chosen pipeline. There are multiple intent classifiers in there (mitie and sklearn) and I think currently they are using similar keys in the models metadata to persist them selfs. What is the reason for using both of them?

**Comment by napster-powergeek** [comment]
Exception: Unable to create text_categorizer_trainer based on data/total_word_feature_extractor.dat


{
  "pipeline": "spacy_sklearn",
  "path" : "./projects",
  "data" : "./data/testdata.json"
}

**Comment by napster-powergeek** [comment]
What should be done?
@tmbo

**Comment by preetamait** [comment]
The error still persists. I've tired multiple configurations but each one keeps giving the same exception. Request you to help me on this.

**Comment by napster-powergeek** [comment]
The error still persists. I've tired multiple configurations but each one keeps giving the same exception. Request you to help me on this.

**Comment by tmbo** [comment]
@napster-powergeek please create a separate issue that includes the whole exception (so complete stack trace) as well as the command you are running.
