### ISSUE TITLE
Issue with train API

### ISSUE THREAD

**Issue by NagarajGond** [golastmile/rasa_nlu#275]
If I hit train API it triggers rasa server and also we don't have option to pass the specific configuration file.

````
curl -XPOST localhost:5000/train -d @data/examples/rasa/demo-rasa.json

ps -ef|grep rasa
root      8382  8057  0 01:32 pts/2    00:00:06 python -m rasa_nlu.server -c config_mitie.json
````

**Comment by tmbo** [comment]
Please do not delete the issue template...What version of rasa nlu are you using?

I am not sure what the error is you are describing. The command looks fine. It doesn't matter what you passed to the server when running it, the train command should use the passed json. So the ps output doesn't tell anything. Is there an error in your training?

**Comment by NagarajGond** [comment]
I was confused since it triggers rasa_nlu.server. Anyway it is working as expected. Please close this thread.
Thank you.

**Comment by tmbo** [comment]
Right got you, we are thinking about restructuring the configuration (to separate configuration of the server and a single model). :)
