### ISSUE TITLE
Confidence value for all the intents

### ISSUE THREAD

**Issue by rajesh-bhat** [golastmile/rasa_nlu#276]
**rasa NLU version** (e.g. `0.7.3`):
0.8.0a1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie

**Operating system** (windows, osx, ...):
osx
**Issue**:
Is there any way to get confidence value for all the intents? 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
In the current master version, we added an intent ranking, that shows the top 10 intents for the sklearn classifier (e.g. using either `mitie_sklearn` or `spacy_sklearn`). Unfortunately, we can't do that with the mitie backend (not provided by the trained models).

The result looks like this:
```json
{
    "text": "I want some italian",
    "entities": [
        {
          "end": 19,
          "entity": "cuisine",
          "start": 12,
          "value": "italian"
        }
    ],
    "intent": {
        "confidence": 0.5192305466357352,
        "name": "restaurant_search"
    },
    "intent_ranking": [
        {
            "confidence": 0.5192305466357352,
            "name": "restaurant_search"
        },
        {
            "confidence": 0.2066287604378098,
            "name": "affirm"
        }
    ]
}
```
Is this intent ranking what you are looking for?

**Comment by rajesh-bhat** [comment]
Thanks a lot. I will try with sklearn classifier, no issues 👍

**Comment by PHLF** [comment]
> we can't do that with the mitie backend

One can use the mitie_sklearn backend to get intent ranking and keep using MITIE features for intent classification (even if not using MITIE built-in classifiers).

**Comment by rajesh-bhat** [comment]
Can you provide sample json response from mitie_skelarn model?

**Comment by PHLF** [comment]
The mitie_sklearn backend's response format is exactly the same as the one mentioned by @tmbo :)

**Comment by rajesh-bhat** [comment]
Thank you  :)
