### ISSUE TITLE
Ability to pass pipeline config via command-line

### ISSUE THREAD

**Issue by angadn** [golastmile/rasa_nlu#286]
Would something like this work here, [in config.py, line 137](https://github.com/golastmile/rasa_nlu/blob/master/rasa_nlu/config.py#L137)?:
```
if all([config.get("pipeline"), isinstance(config.get("pipeline"), str)]):
    config["pipeline"] = [config["pipeline"]]
```

PR: https://github.com/golastmile/rasa_nlu/pull/287

**Comment by tmbo** [comment]
Although, I get this use case I am afraid this is not a solution we can use. The pipeline configuration value can already be a string (e.g. `spacy_sklearn`) to implicate that one wants to use a predefined pipeline.

**Comment by angadn** [comment]
@tmbo When I attempt to pass a string via CLI, it simply picks off the first character from the string and raises an error as Not Found. How would you recommend I revise my solution?

**Comment by tmbo** [comment]
Which version of rasa NLU are you using?

**Comment by angadn** [comment]
The latest - I built it off a fork less than 4 days ago

**Comment by tmbo** [comment]
Can you post an example that shows how you pass the argument so I can test it myself?

**Comment by angadn** [comment]
I have forked since - will try to replicate the bug once again on a fresh base, but this is what I did to get to it: `docker run --name rasa_nlu -e RASA_PIPELINE=nlp_spacey...`

This would give an error saying `n` not found

**Comment by tmbo** [comment]
Alright, could reproduce it. I've added a more useful exception that indicates what is going wrong (not a solution to your problem though).

Since, we are thinking about removing the possibility to pass all arguments via cmd / env I want to understand why you need this. Couldn't you link a directory from inside your container to the hosting machine containing the configuration and set all the values in there?

**Comment by angadn** [comment]
In my use-case, I've created a new Google Cloud Storage persistor, and aim to deploy Rasa NLU clusters, without really relying on volume, or state or a volume, or sharing the volume. Moreover, I've modified Rasa so that it looks up on the bucket directly, without even needing the model_dirs in the config.

It is possible it favours my use-case more than the regular one, but what do you think? In a Docker-environment, passing arguments via command line is very helpful, as it removes the need for a base-image and dramatically simplifies configuration on a cluster (Kubernetes, in my case)

**Comment by twerkmeister** [comment]
The pull request for this issue has been merged already, closing :-)
