### ISSUE TITLE
Improve configuration format

### ISSUE THREAD

**Issue by tmbo** [golastmile/rasa_nlu#291]
Currently all configuration keys are just thrown into one large json. This starts to become very cluttered as we add more and more components. Hence, we need a way to structure the configuration in a better way. 

Idea: bundle component specific configuration values
```json
{
  "pipeline": [
    {
      "component": "nlp_spacy",
      "spacy_model_name": "en"
    },
    {
      "component": "intent_classifier_spacy"
    },
    {
      "component": "ner_spacy",
      "fine_tune_spacy_ner": false
    }
  ],
  "language": "en",
  "num_threads": 1,
  "path": "models",
  ...
}
```
Issues:
- I am not sure we can make passing component specific arguments via cmd / env possible
- if a user uses a pipeline template (e.g. `"pipeline": "spacy_sklearn"`) he can not specify any configuration values. if he wants to change a components configuration he needs to replace the template name with the actual pipeline. (Idea: drop templates all together?)

Thoughts?

**Comment by amn41** [comment]
Yeah the command line / env arg passing was the reason for keeping it flat in the first place. 
I feel like this can't be a unique problem to rasa - there must be a good python config + arguments  module out there?

**Comment by amn41** [comment]
Another idea - we could drop support for commandline args / env vars and just pass a literal JSON as the sole command line arg

**Comment by tmbo** [comment]
All right, as discussed we will only fix the pipeline passing issue for now and stick with the current configuration format.
