### ISSUE TITLE
ImportError: No module named flask; requirement.txt must be manually run

### ISSUE THREAD

**Issue by rmharrison** [golastmile/rasa_nlu#295]
## Problem
**rasa NLU version** 0.8.0a11

For github installation, the README.md states
```
git clone git@github.com:golastmile/rasa_nlu.git
cd rasa_nlu
python setup.py install
```

However, when I run the program...
```
>>> python -m rasa_nlu.server
Traceback (most recent call last):
...
ImportError: No module named flask
```

The requirement install wasn't run.

I get the same issue when installing via pip, i.e. `pip install rasa_nlu`.
Must manually install requirements.txt

Minor issue for the github installation; just trips-up people who don't have much experience in python.
For the pypi installation, more of a concern.

**Comment by devnieL** [comment]
Hello,
I have the same problem.

Thanks.

**Comment by rmharrison** [comment]
Running `pip install -r requirements.txt` to install *all* the requirements should resolve your immediate problem.
