### ISSUE TITLE
Failed to load component 'ner_mitie'

### ISSUE THREAD

**Issue by alvin-reyes** [golastmile/rasa_nlu#297]
**rasa NLU version** (e.g. `0.7.3`):
0.8.0a11
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie
**Operating system** (windows, osx, ...):
Ubuntu 16.04.2 x64
**Issue**:
Error: Failed to load component 'ner_mitie'. Couldn't fill argument 'entity_extractor_mitie' :(
Traceback (most recent call last):
  File "rasa_nlu/data_router.py", line 84, in __create_model_store
    interpreter = Interpreter.load(metadata, self.config, self.component_builder)
  File "rasa_nlu/model.py", line 245, in load
    component = component_builder.load_component(component_name, context, model_config, meta)
  File "rasa_nlu/components.py", line 241, in load_component
    raise Exception("Failed to load component '{}'. {}".format(component_name, e.message))

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline":"mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "num_threads":4,
  "logs":"logs",
  "port":5001,
  "data" : "./data/botTraining.json"
}
```

**Comment by alvin-reyes** [comment]
Closing. Issue is I executed the training using an old version and try to use the model on the new one. Everything works fine now.

**Comment by MiaLinlinLu** [comment]
> Closing. Issue is I executed the training using an old version and try to use the model on the new one. Everything works fine now.

How did you solve that? I installed mitie. With 'rasa train', I have a cannot find nlp_mitie error. I know that mitie is with a lower version rasa_nlu. How could I use mitie in high version rasa?
