### ISSUE TITLE
Error running the trainer with ner_duckling component

### ISSUE THREAD

**Issue by alvin-reyes** [golastmile/rasa_nlu#300]
**rasa NLU version** (e.g. `0.7.3`):
0.8.0a11
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
"nlp_mitie","ner_duckling"

**Operating system** (windows, osx, ...):

**Issue**:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/areyes/rasa_nlu/rasa_nlu/train.py", line 81, in <module>
    do_train(config)
  File "/home/areyes/rasa_nlu/rasa_nlu/train.py", line 70, in do_train
    trainer.validate()
  File "rasa_nlu/model.py", line 164, in validate
    raise Exception("Failed to validate at component '{}'. {}".format(component.name, e.message))
Exception: Failed to validate at component 'ner_duckling'. Couldn't fill argument 'entities' :(

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline":["nlp_mitie","ner_duckling"],
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "num_threads":4,
  "logs":"logs",
  "port":5001,
  "duckling_processing_mode": "append",
  "data" : "./data/charterbot/charterBotTrn.json",
  "token":"3cXuFQdNBae2l/iInieT7Ud3mDVXwZUY"
}
```

**Comment by alvin-reyes** [comment]
I got this working by including the ner_duckling on the "mitie" component on registry.py. I guess there was an overlap on one of the components.

**Comment by tmbo** [comment]
So the thing is, currently the duckling component needs another ner component to be in the pipeline before the duckling component, e.g. `["nlp_mitie", "ner_mitie", "ner_duckling"]`.

To fix this we need some sort of general way to merge the output of different components (e.g. multiple entity detectors), haven't come up with a satisfying solution yet though.
