### ISSUE TITLE
doc - "Using rasa NLU from python" does not work

### ISSUE THREAD

**Issue by oziee** [golastmile/rasa_nlu#302]
**rasa NLU version** (e.g. `0.7.3`):
0.8

**Operating system** (windows, osx, ...):
ubuntu

**Issue**:

doc file on using rasa NLU from python example doesn't work
http://rasa-nlu.readthedocs.io/en/stable/python.html

`from rasa_nlu.interpreters.spacy_sklearn_interpreter import SpacySklearnInterpreter
from rasa_nlu.model import Metadata
import spacy

metadata = Metadata.load("/path/to/model_dir")
nlp = spacy.load("en")
interpreter = SpacySklearnInterpreter.load(metadata, nlp=nlp)`

>>> from rasa_nlu.interpreters.spacy_sklearn_interpreter import SpacySklearnInterpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named interpreters.spacy_sklearn_interpreter

can we get an updated example?

**Comment by amn41** [comment]
Thanks - but this has already been updated. You need the [latest](http://rasa-nlu.readthedocs.io/en/latest/python.html) docs to go with the github version

**Comment by oziee** [comment]
oh i looked, but only saw v0.7x listed.. didn't think of clicking "latest"
