### ISSUE TITLE
 Pipeline components tokenizer_whitespace and tokenizer_spacy errors

### ISSUE THREAD

**Issue by AndriiKr** [golastmile/rasa_nlu#308]
**rasa NLU version** (e.g. `0.8.0a11`):

**Used backend / pipeline** ("nlp_spacy", "nlp_mitie", "tokenizer_whitespace", "ner_mitie", "ner_synonyms"):

**Operating system** (Linux):

**Issue**:
When using  "tokenizer_whitespace" or  "tokenizer_spacy":
```
  File "trainer.py", line 106, in training
    trainer = Trainer(RasaNLUConfig("config_mitie.json"))
  File "build/bdist.linux-x86_64/egg/rasa_nlu/model.py", line 119, in __init__
    components.validate_requirements(config.pipeline)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/components.py", line 89, in validate_requirements
    for package in component_class.required_packages():
AttributeError: 'NoneType' object has no attribute 'required_packages'
```

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": ["nlp_spacy", "nlp_mitie","tokenizer_spacy", "ner_mitie", "ner_synonyms"],
  "language": "en",
  "num_threads": 1,
  "mitie_file": "../../MITIE-models/english/total_word_feature_extractor.dat",
  "fine_tune_spacy_ner": false,
  "max_number_of_ngrams": 7,
  "duckling_processing_mode": "append",
  "entity_crf_BILOU_flag": false,
  "entity_crf_features": [
    ["low", "title", "upper", "pos", "pos2"],
    ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2"],
    ["low", "title", "upper", "pos", "pos2"]]
}
```

**Comment by tmbo** [comment]
Thanks, fixed it. These components were not registered so they couldn't be created.

**Comment by Nitinvermaa1** [comment]
Hi ,
I facing the issue while sending curl post. Below are the details.

Python version:3.6.5
Rasa_Core Version: 0.11.3
Rasa_NLU Version: 0.13.2

/GET are working fine
--> >curl -H "Accept: application/json" -H "Content-Type: application/json" -XGET localhost:5005/domain

Response:{"actions":["utter_greet","utter_get_pizza_size","utter_get_pizza_toppings","action_order_pizza"],"config":{"store_entities_as_slots":true},"entities":["size","toppi
ngs"],"intents":[{"order_pizza":{"use_entities":true}},{"greet":{"use_entities":true}}],"slots":{"size":{"initial_value":null,"type":"rasa_core.slots.TextSlot"},"top
pings":{"initial_value":null,"type":"rasa_core.slots.TextSlot"}},"templates":{"utter_get_pizza_size":[{"text":"What pizza size?"}],"utter_get_pizza_toppings":[{"text
":"What toppings would you like on your pizza?"}],"utter_greet":[{"text":"Hello, how can I help you?"},{"text":"Hi, I am here to help."}]}}

Where as while for /post method I'm getting error

>curl -H "Accept: application/json" -H "Content-Type: application/json" -XGET localhost:5005/webhooks/rest/webhook -d '{"text":"Hello"}'

Response: 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

Rasa_core provide the method 
custom_webhook.receive    OPTIONS, POST   /webhooks/rest/webhook

**Comment by tmbo** [comment]
Please create your own issue. this does not seem related to this one.
