### ISSUE TITLE
rasa fails to start

### ISSUE THREAD

**Issue by bigman73** [golastmile/rasa_nlu#317]
Python 3.6.1 (32 bit and I also tried with 64 bit) on Windows 7 Enterprise 64 bit
rasa-nlu (0.7.4)

I followed the Getting Started section and installed rasa_nlu using pip:
pip install rasa_nlu

It successfully installed (and pip list shows it).

When I try to start the rasa_nlu server using the command:
python -m rasa_nlu.server

I get this error:
```
Traceback (most recent call last):
  File "C:\python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\python36\lib\site-packages\rasa_nlu\__init__.py", line 5, in <module>
    import version
ModuleNotFoundError: No module named 'version'
```

**Comment by tmbo** [comment]
@bigman73 the version on pypi doesn't support python 3 yet. You need to run the current master if you want python 3 support. Otherwise you need till we release this version in a couple of days to pypi.

**Comment by bigman73** [comment]
Thanks, I understand.
I think there should be a large note with this current constraint, but I'll wait for next week.
