### ISSUE TITLE
mitie train num_threads is always 1

### ISSUE THREAD

**Issue by xliuhw** [golastmile/rasa_nlu#323]
**rasa NLU version**  = 0.7.4:

**Used backend ** = `mitie`:

**Operating system** Ubuntu 14 and 16:

**Issue**:
I tried to set num_threads to a number which is no than one, e.g. I set in my config file:
"num_threads": 4,

but it always shows 1:

now do training
C:           20
epsilon:     0.01
num threads: 1
cache size:  5

I tried both the stable version and the latest version of rasa_nlu and they both display:
num threads: 1
And when I look at the number of process from "top", it looks like just one process is running.
When I directly call train_ner.py from mitie, it displays the right number of the threads, e.g. 
num_threads: 4

Has any body successfully used the number of more than one from rasa_nlu?

Thanks!

```

**Comment by tmbo** [comment]
Thanks for that report, should be fixed in the latest master (just pushed a fix for it).
