### ISSUE TITLE
Issue on running python server of latest version to load old trained models

### ISSUE THREAD

**Issue by xliuhw** [golastmile/rasa_nlu#326]
Hi I am running the latest version of rasa. When I try to run the python server to load the old models trained by my previous the stable version. (there is no problem for the python server to load the models trained via the same latest version). I got the following error:
```
INFO:root:Loading model './trained_models/model_20170412-191413-RealAnno1-MoreEntities'...
ERROR:root:Failed to load model './trained_models/model_20170412-191413-RealAnno1-MoreEntities'. Error: Failed to load component 'ner_mitie'. Couldn't fill argument 'entity_extractor_mitie' :(
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/rasa_nlu/data_router.py", line 87, in __create_model_store
    model_store[alias] = self.__interpreter_for_model(model_path)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/data_router.py", line 71, in __interpreter_for_model
    return Interpreter.load(metadata, self.config, self.component_builder)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/model.py", line 218, in load
    component = component_builder.load_component(component_name, context, model_config, meta)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/components.py", line 349, in load_component
    raise Exception("Failed to load component '{}'. {}".format(component_name, e))
Exception: Failed to load component 'ner_mitie'. Couldn't fill argument 'entity_extractor_mitie' :(
```
Is this a bug or something I've missed?

Thanks!

**Comment by tmbo** [comment]
Right so we did a couple of breaking changes while developing the new version (breaking changes with respect to the previously released 0.7.x as well as between the different versions of 0.8.0aX). 

Best is to retrain the model. Otherwise you can try to fix this error (and let's see if there are others), by replacing the key `entity_extractor ` in the models `metadata.json` with `entity_extractor_mitie `.

**Comment by xliuhw** [comment]
Okay, I see! Thanks for the suggestions!
How about trained from the latest version but deployed in the release 0.7.x installation?
Possible problems?

**Comment by tmbo** [comment]
No that won't work either. I am very sorry for that, but at this point in time we still need the freedom of doing breaking changes (hence the 0.X version), but we are working very hard on creating a good architecture for 1.X to avoid this in the future.

**Comment by xliuhw** [comment]
Okay, many thanks for you guy's hard work! I think this thread can be closed now. I close it now.
