### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by skbalahere** [golastmile/rasa_nlu#329]
**Operating system** (windows, ):

**Issue**: I am not able to run server and getting below Error
![image](https://cloud.githubusercontent.com/assets/5198993/25698108/2e31c4be-30db-11e7-8553-50e22b89a8a0.png)

**Comment by amn41** [comment]
did you install from PyPI or github?

**Comment by skbalahere** [comment]
I have installed through this command pip install rasa_nlu. Sorry am very new to this

**Comment by tmbo** [comment]
The version on pypi doesn't support python 3 yet. So you either need to use python 2 or install the current master version from github (https://github.com/golastmile/rasa_nlu#a-install-locally)

**Comment by skbalahere** [comment]
ok i will try and let you know the results
