### ISSUE TITLE
Wrong entity detection by mitie (entity from previous query showing up)

### ISSUE THREAD

**Issue by sourjatilak** [golastmile/rasa_nlu#347]
**rasa NLU version** (e.g. `0.7.3`): 0.8.0a17

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): mitie_sklearn

**Operating system** (windows, osx, ...): redhat el7 x86_64

**Issue**:

The entity detection of mitie is detecting entities of previous query.
Suppose:

 Query1: What is Xyz?  Response:  Intent: data_info, info_name: "Xyz"

 Query2: Who is Abc? Response: Intent: data_bio, bio_name: "Abc", info_name: "Xyz"

This issue was not happening in previous versions like 0.8.0a13
The version of mitie installed is mitie==0.2.0

**Content of configuration file** (if used & relevant):
{
  "pipeline": "mitie_sklearn",
  "mitie_file": "./total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./rawdata/dataset09052017_1303.json",
  "server_model_dirs":"model_20170509-133521",
  "response_log":"response_log",
  "emulate":"wit"
}

**Comment by tmbo** [comment]
duplicates #346 . this is fixed in latest master and the most recent version on pypi (0.8.2)
