### ISSUE TITLE
Getting Multiple duplicate responses on every refresh 

### ISSUE THREAD

**Issue by Sureshkumars** [golastmile/rasa_nlu#349]
**rasa NLU version** (e.g. `0.8.0`):

**Used backend / pipeline** (`mitie`)

**Operating system** ( osx, Ubuntu...):

**Issue**:
I cloned a github version of rasa_nlu and when I run the server with testing models mitie, I am getting multiple irrelevant duplicate entity responses each time when I am refreshing the parse request tab

{
  "entities": [
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }, 
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }, 
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }, 
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }, 
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }, 
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }, 
    {
      "end": 18, 
      "entity": "keyword", 
      "extractor": "ner_mitie", 
      "start": 5, 
      "value": "is windows 10"
    }
  ], 
  "intent": {
    "confidence": 0.4575535961132984, 
    "name": "search"
  }, 
  "text": "what is windows 10"
}

**Content of configuration file** (if used & relevant):
```json

config_mitie.json
{
  "pipeline": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/sampledata.json"
}


                             

```

**Comment by twerkmeister** [comment]
This seems to be related to the 0.8.0 release bug. Could you verify you are still experiencing it with the latest version (master or 0.8.2)? Thanks!

**Comment by Sureshkumars** [comment]
@twerkmeister  I am facing this issue with the version I cloned from github repository

**Comment by tmbo** [comment]
@Sureshkumars please run `python -c "import rasa_nlu; print rasa_nlu.__version__"` and let us know the version you are using.

**Comment by Sureshkumars** [comment]
@tmbo Am using '0.8.4' version

**Comment by tmbo** [comment]
Can you please post the `metadata.json` of the stored model you are using?

**Comment by Sureshkumars** [comment]
{
    "entity_synonyms": "entity_synonyms.json", 
    "pipeline": [
        "nlp_mitie", 
        "tokenizer_mitie", 
        "ner_mitie", 
        "ner_synonyms", 
        "intent_classifier_mitie"
    ], 
    "mitie_feature_extractor_fingerprint": 10023965992282753551, 
    "language": "en", 
    "mitie_file": "./data/total_word_feature_extractor.dat", 
    "intent_classifier_mitie": "intent_classifier.dat", 
    "trained_at": "20170508-184350", 
    "training_data": "training_data.json", 
    "entity_extractor_mitie": "entity_extractor.dat", 
    "rasa_nlu_version": "0.8.0a17"
}


@tmbo

**Comment by tmbo** [comment]
@Sureshkumars please make sure you are using the latest version (as you can see in the model metadata, this model was trained using 0.8.0a17). I think this might just be a path / virtualenv issue or something (you are basically not using the version you think you are using). The model should show 0.8.4

**Comment by Sureshkumars** [comment]
Sure will do the same @tmbo

**Comment by Sureshkumars** [comment]
Issue resolved. When I use the rasa with the PIP version @tmbo  But If i clone directly from the github am facing the issue again.

**Comment by tmbo** [comment]
cool, I'll close this one then.
