### ISSUE TITLE
How to deal with case?

### ISSUE THREAD

**Issue by znat** [golastmile/rasa_nlu#350]
**rasa NLU version** (e.g. `0.7.3`):0.8.2

**Used backend / pipeline** :[nlp_spacy,ner_crf,ner_synonyms]

I'm training a model where I'm extracting cities. Cities are capitalized in the training data (e.g. 'Paris') but the model will fail with lowercase instances such as 'paris'. 

How do you recommend dealing with this (besides doubling the training set with lowercase cities)?
Thanks

**Comment by twerkmeister** [comment]
@tmbo could this be a new problem with the crf component or was it the same for spacy/mitie too?

**Comment by amn41** [comment]
You can make the crf case-insensitive by passing a custom list of features which excludes the 'title' feature, see https://github.com/golastmile/rasa_nlu/blob/master/rasa_nlu/extractors/crf_entity_extractor.py#L45

**Comment by xliuhw** [comment]
this has occurred to me as well a while ago on mitie (and on API.AI). My temporary solution was converting them all to lower case. I thought it would be good feature for training when keeping the capitalised word, am I right?

**Comment by znat** [comment]
Thanks @amn41 . How do I invoke the constructor? The crf is defined in the pipeline in the `config.json` file?

**Comment by amn41** [comment]
to customise this you'll have to clone the repo, edit the code directly, and install with `python setup.py install`

**Comment by antoniobertob** [comment]
I had the same issue too, I fixed it with the @xliuhw 's temporary solution. I'm using spacy_sklearn/Api.ai.

**Comment by RickD123** [comment]
Can somebody please provide a full example? I am using Rasa with spacy_sklearn - can somebody explain to me how I can use a case-insensitive crf?

**Comment by ievgennaida** [comment]
The same problem with tensorflow

**Comment by akelad** [comment]
Please create a  new issue
