### ISSUE TITLE
Error when emulating Luis

### ISSUE THREAD

**Issue by saileshg86** [golastmile/rasa_nlu#353]
**rasa NLU version** (e.g. `0.7.3`): 0.8.2

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): "spacy_sklearn"

**Operating system** (windows, osx, ...): Ubuntu 14.04.4 LTS

**Issue**: 
I've a trained model and it runs fine except when its asked to emulate Luis. I tried setting `"emulate" : "wit"`,`"emulate" : "api"` and the response is fine. However, on setting `"emulate" : "luis"` in the config json file, I get an Internal Server Error (500)as the response.
Could you please have a look if this is happening ?

Thanks

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/acad_training_data.json",
  "emulate": null
}

```

**Comment by tmbo** [comment]
@saileshg86 thanks, just fixed that. the current version on master already contains the change. the build hasn't completed yet but in about 2h the version (0.8.3) will also be available on pypi.
