### ISSUE TITLE
rasa 0.8.2 fails to start with Python 3.6

### ISSUE THREAD

**Issue by bigman73** [golastmile/rasa_nlu#354]
I opened another ticket 12 days ago about 0.7.4 and was asked to wait for a new version.

The new version, 0.8.2, is indeed in PyPi but now there is a new error message when trying to run the server with "python -m rasa_nlu.server", per the instructions:
```
"Traceback (most recent call last):
  File "C:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python36\lib\site-packages\rasa_nlu\server.py", line 10, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```

Please advise,
Thanks

**Comment by tmbo** [comment]
@bigman73 How did you install the package?

**Comment by bigman73** [comment]
`pip install rasa-nlu
Collecting rasa-nlu
  Downloading rasa_nlu-0.8.3.tar.gz
Requirement already satisfied: requests in c:\python36\lib\site-packages (from rasa-nlu)
Requirement already satisfied: pathlib in c:\python36\lib\site-packages (from rasa-nlu)
Requirement already satisfied: cloudpickle in c:\python36\lib\site-packages (from rasa-nlu)
Requirement already satisfied: boto3 in c:\python36\lib\site-packages (from rasa-nlu)
Requirement already satisfied: typing in c:\python36\lib\site-packages (from rasa-nlu)
Requirement already satisfied: botocore<1.6.0,>=1.5.0 in c:\python36\lib\site-packages (from boto3->rasa-nlu)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\python36\lib\site-packages (from boto3->rasa-nlu)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in c:\python36\lib\site-packages (from boto3->rasa-nlu)
Requirement already satisfied: docutils>=0.10 in c:\python36\lib\site-packages (from botocore<1.6.0,>=1.5.0->boto3->rasa
-nlu)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\python36\lib\site-packages (from botocore<1.6.0,>=1.5.0
->boto3->rasa-nlu)
Requirement already satisfied: six>=1.5 in c:\python36\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.6
.0,>=1.5.0->boto3->rasa-nlu)
Installing collected packages: rasa-nlu
  Running setup.py install for rasa-nlu ... done
Successfully installed rasa-nlu-0.8.3`

**Comment by bigman73** [comment]
Why is this ticket closed? My problem isn't solved and you provided no information.

**Comment by tmbo** [comment]
@bigman73 sorry, I made a comment here that apparently didn't make it through the spotty train connection. The issue got closed by a commit that should fix your issue, the corresponding package with version 0.8.5 should be available on pypi in about an hour.

**Comment by tmbo** [comment]
or you can install directly form github if you want to have that version quicker.

**Comment by bigman73** [comment]
0.8.5 is confirmed to work with Python 3.6!

Thanks.
