### ISSUE TITLE
multitenancy support

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#36]
This suggestion also comes from @3x14159265 . 
Idea is to have rasa NLU provide multiple `apps`, e.g. have several models loaded into memory and serve requests based on them (routed by the URL). 

The simplest approach is to start a separate server for each model, and use a supervisor. But each process will have word vectors loaded into memory, which means you can't fit very many on a server.

A better way would be to have several models loaded within one server, although I think only the `spaCy` backend would actually be able to share the large memory component between them. Would probably be doable to modify MITIE to support that as well. 

To help plan this out, would be really helpful if people wrote their intended deployment setup here, so we can discuss various trade-offs.

**Comment by plauto** [comment]
Personally I like more the idea of having several models served by one server...although I think that the implications on that over spacy and MITIE would have been well investigated.

So basically you would have a /models/flights or /models/restaurants right? each one of them would then be able to answer queries at /models/flights/parse?q=flight from Tokyo to Munich

**Comment by baregawi** [comment]
Just an idea: use multiprocessing's Process class to spawn processes from a "main" process then use it's Queue class to implement a facade over Spacy, MITIE and anything that has a heavy memory footprint or a long start-up time. That way those things only run in the "main" process as long as they can be shared.

**Comment by amn41** [comment]
thanks for the input @baregawi - you guys are on AWS right? so would you run this on elastic beanstalk or just a regular VPS?

**Comment by baregawi** [comment]
For our main servers, we use Flask as our application framework and deploy it through AWS CodeDeploy at the moment since our application is not simple enough for Heroku or Elastic Beanstalk. But I imagine that if we contribute models to rasa_nlu they will be our individual ML/NLP modules which are all Python classes at the moment.

**Comment by samhavens** [comment]
FWIW we use AWS and Joyent. On AWS, we use Elastic Beanstalk and EC2, moving towards doing more with just EC2. Jenkins triggers everything. We use nginx/hapi/node and, when using python, nginx/gunicorn/flask/python.

On one hand, I like calling the scripts directly without the network overhead. But on the other hand, I know for our case, we can't guarantee that rasa will be on the same machine as the application (we can almost guarantee it won't be)... so we will have to call it over the network anyway.

**Comment by samhavens** [comment]
Under what conditions is it better to train a new model?
