### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by chemalopezp** [golastmile/rasa_nlu#378]
Hi team,

Both installing from pip and from github, I am having this issue when installing related components:

Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.6.0,>=1.5.0->boto3==1.4.4->-r requirements.txt (line 4))
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Installing collected packages: gevent, itsdangerous, Werkzeug, MarkupSafe, Jinja2, click, flask, six, python-dateutil, botocore, s3transfer, boto3, typing, future, functools32, jsonschema, pathlib, c
loudpickle, rasa-nlu
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/gevent'

 

**rasa NLU version** (e.g. `0.7.3`): 0.8.6
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
**Operating system** (windows, osx, ...): macOS Sierra 10.12.4
**Issue**: Can't complete installation
**Content of configuration file** (if used & relevant):
```json

```
Thanks

**Comment by tmbo** [comment]
What is the exact command you executed?

**Comment by chemalopezp** [comment]
First I tried with
`pip install rasa_nlu`
but didn't work, so I tried to clone the github repo and installed the requirements (that's the log I showed)
`pip install -r requirements.txt`
Thanks!

**Comment by tmbo** [comment]
can you manually install gevent? e.g. `pip install gevent=0.4.10`

**Comment by chemalopezp** [comment]
Still getting some issues:
`Joses-MacBook-Pro:rasa_nlu joselopez$ pip install gevent==0.4.10
Collecting gevent==0.4.10
  Could not find a version that satisfies the requirement gevent==0.4.10 (from versions: 0.9.2, 0.9.3, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 1.0, 1.0.1, 1.0.2, 1.1a1, 1.1a2, 1.1b1, 1.1b2, 1.1b3, 1.1b4, 1.1b5, 1.1b6, 1.1rc1, 1.1rc2, 1.1rc3, 1.1rc4, 1.1rc5, 1.1.0, 1.1.1, 1.1.2, 1.2a1, 1.2a2, 1.2.0, 1.2.1)
No matching distribution found for gevent==0.4.10
Joses-MacBook-Pro:rasa_nlu joselopez$ pip install gevent
Collecting gevent
  Using cached gevent-1.2.1-cp27-cp27m-macosx_10_6_intel.whl
Requirement already satisfied: greenlet>=0.4.10 in /Library/Python/2.7/site-packages (from gevent)
Installing collected packages: gevent
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/gevent'`

Is there any requirement I should be aware?

Thanks

**Comment by tmbo** [comment]
This isn't a rasa nlu issue. It is an issue with your local pip setup &permissions. Try installing in user mode `pip install --user -r requirements.txt` / `pip install --user rasa_nlu` or by using `sudo` (not recommended).

**Comment by chemalopezp** [comment]
Thanks Tom, that solved the issue.

**Comment by surya103** [comment]
I have the same error and --user option too is not helping. Anything else, I might be missing??

**Comment by PHLF** [comment]
As Tom said, easy but ugly fix : 

> by using `sudo`

I would advise you to use a [virtualenv](https://packaging.python.org/guides/installing-using-pip-and-virtualenv/) instead.

**Comment by surya103** [comment]
Thanks for the response. Sudo too, didnt work. Here is the error message...

Installing collected packages: greenlet, gevent, constantly, incremental, attrs, Automat, hyperlink, Twisted, werkzeug, klein, jmespath, futures, docutils, botocore, s3transfer, boto3, typing, future, tqdm, certifi, chardet, idna, urllib3, requests, functools32, jsonschema, numpy, simplejson, rasa-nlu, singledispatch, backports-abc, tornado, nose
  Running setup.py install for greenlet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-M7Np__/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jj8L2i-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.macosx-10.13-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c greenlet.c -o build/temp.macosx-10.13-intel-2.7/greenlet.o
    creating build/lib.macosx-10.13-intel-2.7
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.13-intel-2.7/greenlet.o -o build/lib.macosx-10.13-intel-2.7/greenlet.so
    running install_lib
    copying build/lib.macosx-10.13-intel-2.7/greenlet.so -> /Library/Python/2.7/site-packages
    running install_headers
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-M7Np__/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jj8L2i-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-M7Np__/greenlet/

**Comment by PHLF** [comment]
It sounds like you're using a [joke of an operating system](https://github.com/gevent/gevent/issues/679) 😄 

The answer to your issue is to use virtualenv as I previously mentionned.

Not related to your issue, but on Github/Gitter try to put code snippets or console outputs between \`\`\` like this:

\`\`\`
Code sample
\`\`\`

That will improve readability.

**Comment by surya103** [comment]
Thank you. Figured out the problem. This issue seems to be post El Captain update on Mac, which prevents updating /System/Libray/Frameworks/Python/xxxx .

Found a workaround by using "pip install --user rasa_nlu" !
Thanks for your help.
