### ISSUE TITLE
logging verbosity options

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#41]
I think we should give the user some control over the level of logging output. 

option 1: default is to be very verbose, make a `-q quiet` command line flag to suppress

option 2: default is minimal logging, make `-v verbose` flag to help debugging

**Comment by tmbo** [comment]
I'd go for a logger (https://docs.python.org/2/library/logging.html) and let the user decide on the log level. Set it to `info` or `warn` by default

**Comment by amn41** [comment]
cool. I think we should also print the final configuration when the program starts

**Comment by amn41** [comment]
address in PR #58
