### ISSUE TITLE
Visualizer has trouble rendering overlapping entities

### ISSUE THREAD

**Issue by yulkes** [golastmile/rasa_nlu#42]
Same word appears multiple times if it is included in overlapping entities.

![image](https://cloud.githubusercontent.com/assets/2720630/20926084/3a91144a-bbc3-11e6-91e1-ebf968d5ef9a.png)

Expected behaviour: All matching entity types appear at the end of the matched word

**Comment by amn41** [comment]
this is an interesting use case. actually I think MITIE would fail in this case. IIRC it doesn't support overlapping entities. But yes this should be fixed

**Comment by amn41** [comment]
@yulkes would something like this work? 
![image](https://cloud.githubusercontent.com/assets/5114084/21006643/b7f3e9f2-bd31-11e6-8f1b-2c87d7c577e1.png)
see PR #47
