### ISSUE TITLE
server should handle nonascii text

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#44]
if we add some non-ascii text in `test_post_parse()` the encoding isn't right. see lines 57-59 in `test_server.py`

```python
        req = requests.post(http_server + "/parse", json={"q": u"hello ńöñàśçií"})
        expected = [{"entities": {}, "confidence": None, "intent": "greet", "_text": "hello ńöñàśçií"}]
       assert req.status_code == 200 and req.json() == expected
```

this fails

**Comment by plauto** [comment]
should be fixed! We were not decoding properly the request that was coming from the client (both in /parse GET and POST); now it should be OK.

At the same time I have found some minor issues with the emulators, in the way entities were handled.

**Comment by amn41** [comment]
cool I created a PR #46 - any commits you push to the `unicode-server` branch will automatically update the PR
