### ISSUE TITLE
simple web app for creating training data

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#52]
I'm sure some users will want some kind of GUI for rasa NLU.

We currently have the `visualizer` which can render training data. Would be cool to have a simple web app which can create formatted training data files, similarly to the wit.ai / LUIS interfaces. 

Just comment here if you would like to work on it, or have suggestions on how it should be done

**Comment by amn41** [comment]
thanks @dantodor - I think this will likely be a javascript app

**Comment by dantodor** [comment]
I would suggest then Elm :)

**Comment by benbrown** [comment]
I have 3/4 of this done in a Node app if that would be helpful! I built it as a wrapper to some Node-based NLP tools, but could easily be hooked to rasa!

**Comment by amn41** [comment]
cool stuff @benbrown ! do you have a repo you can point to?

**Comment by azazdeaz** [comment]
Hi, i would be happy to do this one :)

I just started with NLP and chatbots a few months ago, so i'm not an expert but if you tell me what the app has to do i will implement it with nodejs and react.

If i see right we need a command line tool that launches a webapp on localhost which can edit the trainingdata.json-s and maybe run some commands.

You can reach me in email to fix the details if you like :)

**Comment by amn41** [comment]
Hey @azazdeaz ! Sounds awesome 👍  . We had in mind something similar to the wit.ai / LUIS Interfaces, where users can 
1. type in sentences to get labeled
2. choose the intent that matches the sentence
3. highlight particular words to define them as entities

This data should then get saved to a `json` file in the format of https://github.com/golastmile/rasa_nlu/blob/master/data/examples/rasa/demo-rasa.json

**Comment by nmstoker** [comment]
A proper web tool definitely looks like the way forward, but as a stop-gap measure, perhaps something along the lines of this simple spreadsheet would help people with quickly producing formatted training data?

https://docs.google.com/spreadsheets/d/1kZyi68cywCUdgE8P6L61u9SqnaXrKoUFi9F99ghP4Oc/edit?usp=sharing

I hope I've got the format okay (???) It should be accessible to everyone (I think you'll need to save a copy yourself to be able to edit that version)

There's a bit of an inconvenience currently when copying the JSON out to a text editor (it ends up surrounded with double-quotes and the double-quotes in the content get turned into double double-quotes, so this needs to be undone with some quick find-and-replace operations).

**Comment by ToferC** [comment]
Hey all,

I put together a simple script to create training json data either through a CSV import or via text entry on the command line.  It works fine on its own, but would also be pretty simple to convert over to a django app or other web GUI.  I'll create a pull request shortly.

**Comment by ToferC** [comment]
Question: I've written the script in Python 3 to take advantage of starred expressions in reading CSVs. Is this worthwhile putting up?

**Comment by azazdeaz** [comment]
Hi, i'm done with the basics :) 
### [repo](https://github.com/azazdeaz/rasa-nlu-trainer)
### [online demo](https://azazdeaz.github.io/rasa-nlu-trainer/)
For now, it's only editing the examples in the `rasa_nlu_data.entity_examples`. I don't know for sure how json file should be structured, some docs would be very helpful :) ([issue](rasa_nlu_data.entity_examples))

I'm not using rasa_nlu at the moment, so let me know if you have an idea to make it a better tool :)

**Comment by nmstoker** [comment]
Looks excellent. The entity selection of text works well, even on mobile
(am using Chrome on Android)

**Comment by ToferC** [comment]
That looks awesome! You can grab/check JSON generation from my script here.

It sets things up in rasa nlu readable format.

https://github.com/ToferC/rasa_nlu/blob/master/generate_rasa_json.py

**Comment by amn41** [comment]
this is awesome! going to look into it more closely

**Comment by amn41** [comment]
@ToferC  mean adding some metadata fields to the json? like a list of all the intents and entities which occur?

**Comment by ToferC** [comment]
@amn41 - yes. Would help with consistent labelling and in automating training data creation. For example, in my script, I ask for all intents & entities up front to speed labelling as text is entered. In a Web GUI, this info could be pulled into drop downs or auto-suggest fields. 

The other solution is to create a set and just add to it as you go through.

**Comment by azazdeaz** [comment]
Collecting the different intent/entity types from the examples and using them in autocomplete fields is working well in the web app.
But if the intents/entities are going to have more complex properties (like synonyms for values) then it would be very useful.

**Comment by amn41** [comment]
so @azazdeaz 's awesome contribution means I think I can close this issue :) further discussions should happen at https://github.com/azazdeaz/rasa-nlu-trainer
