### ISSUE TITLE
server response

### ISSUE THREAD

**Issue by dantodor** [golastmile/rasa_nlu#54]
First of all, thanks for the great work!
I'm by all means no Python expert, I just wanted to try how this server works, and have encountered several issues down the road, some I could solve them, some not ... So, from the beginning:
- numpy must be installed, maybe I missed that in the docs, but it threw error prior to install it
- while trying to train, after installing MITIE following the steps in the docs, it won't work, at least in my setup, unless I give some extra params on the command line; the full command line I had to use is 
`python -m rasa_nlu.train -c config.json -b mitie -d data/demo-rasa.json -p model`
Despite the fact mitie is configured in config.json, if I'm missing that on the command line, trainer will throw error by picking 'keyword' and saying it's not implemented. The same for the rest of the parameters.
- after training is finished, I'm running the server as advised in the docs. Here I have two issues: I can't see the  file with commands sent to the server, it's not being created, but more important, no matter what text I send for analysis, the server constantly answers like this:
`{"error": "Invalid parse parameter specified"}` 
Command line is the advised one:
`curl -X POST -d '{"text":"I am looking for Chinese food"}' http://localhost:5000/parse`

Can you please tell me what I'm doing wrong ? Where should I look for hints ?

Thanks a lot!

**Comment by amn41** [comment]
Thanks for creating this issue! Let me try to help. Did you install the master brach? we've had some bugfixes recently so maybe `git pull` to update will fix some of these already. 

1. you're totally right - at the moment we do require numpy. See #55

2. will make it easier to debug configuration options. but I think updating your clone should fix this. 

3. this looks like a naming clash. try replacing your json with `'{"q":"I am looking for Chinese food"}'` - I will chase up and update the docs

**Comment by amn41** [comment]
see also issue #57

**Comment by amn41** [comment]
cool both PRs are merged. Please clone latest version and let me know how it goes!
