### ISSUE TITLE
Add confidence level to entities and intent 

### ISSUE THREAD

**Issue by guillegette** [golastmile/rasa_nlu#64]
Would be great to return the confidence for an intent and/or entity, how does it work at the moment? does it return the _best_ match ? Happy to help implementing this as well :)

**Comment by nmstoker** [comment]
This would be useful, because it could enable handling of fallback intents, which API.AI has but I assume aren't included/possible in Rasa as it is currently (is that right?)

**Comment by amn41** [comment]
Yes that's right. What does work is to train a generic intent like `none` or `outofscope`. I could see how a confidence value would be really nice to have though.

**Comment by designerkamal** [comment]
@amn41 Any thoughts on how to train a good `none` intent, like the one that comes with Luis.

**Comment by amn41** [comment]
@designerkamal In my experience it works quite well to just have a bunch of "out of scope" sentences labelled as `None`. This seems to generalise quite well. If you are having trouble please feel free to email me and I will think of ways you can improve perf :)

**Comment by guillegette** [comment]
awesome!!

**Comment by ruchambapat** [comment]
what is the logic behind deciding the confidence value? Is there any threshold? I want to know this for designing my chatbot
