### ISSUE TITLE
Build a Botkit Middleware

### ISSUE THREAD

**Issue by benbrown** [golastmile/rasa_nlu#65]
Botkit is a Node-based tool for building bots. Many developers use API-powered NLP tools right now via a middleware system.

We should create a middleware for Botkit that:

* sends messages received by the bot to the developer's rasa endpoint, amends the message with intent and entity information
* exposes a trigger conditional that allows the bot to 'hear' intents from rasa

Though the specific details will be different, this will be virtually identical in form to any of the other NLP middlewares, such as botkit-wit:
https://github.com/SnowStormIO/botkit-witai

**Comment by benbrown** [comment]
I am nothing if not enthusiastic! I've started a project and have a mvp ready to take a look at.

https://github.com/howdyai/botkit-rasa

**Comment by tmbo** [comment]
Cool idea :+1:

**Comment by amn41** [comment]
Super cool! Let's figure out a testing environment.

**Comment by samhavens** [comment]
Hi @benbrown !

Since rasa can emulate the output of witai, the easiest way to get this integration is to have rasa emulate witai, then use Botkit's wit integration!

**Comment by benbrown** [comment]
@samhavens true! true of all the nlp middlewares, but I think better to have its own since it will likely evolve its own features.
