### ISSUE TITLE
Apache license problematic for vendorizing code, e.g. visualizer

### ISSUE THREAD

**Issue by honnibal** [golastmile/rasa_nlu#70]
Hi,

First, congrats on the launch! Glad to see the Python NLP ecosystem getting even stronger. We're rolling out more spaCy models early next year that should be relevant to you guys.

I noticed some administrivia I'd like to raise, though. It's useful to get these things straightened out early...

I see you guys have chosen to go with the Apache license. I think this might be a problem, because it means you'll have to think carefully about the licensing of code that ends up in your repository.

There's already an example of the problem in rasa's [entity visualizer](https://github.com/golastmile/rasa_nlu/pull/40), which includes code copy-pasted from [our entity visualizer](https://demos.explosion.ai/displacy-ent/ ). The relevant commit is [here](https://github.com/golastmile/rasa_nlu/pull/40/commits/aefc3703e35767a8e34d443cf1b867867713ab14#diff-49c4dc37cb67cca81c2f9923d69f99a0).

If you make Rasa MIT licensed, you'll be able to cut-and-paste code from MIT libraries like this, so long as you attribute it. But if you keep Rasa under the Apache license, you'll only be able to include Apache licensed code in the library.

While this isn't a big deal for the visualizer, you could later get some substantial patches that are actually sourced from an MIT library, without you knowing it. By distributing this under the Apache license, you'll be giving people the impression that they don't need to attribute the code to the original author. You won't be able to fix this problem by simply adding an attribution line — you'll have to delete the code, or change your license.

Matt

**Comment by amn41** [comment]
Hi Matt! Thanks a lot for raising this. I meant to get in touch about the visualizer code before pushing the change, but in the rush of launching I forgot. So firstly, very sorry about that. 

"if you keep Rasa under the Apache license, you'll only be able to include Apache licensed code in the library"
Wasn't aware of this limitation - that's a really interesting point! We did also consider the MIT license, and may reconsider this again.

**Comment by amn41** [comment]
closing this, see #108
