### ISSUE TITLE
Wrong indexing for entity strings

### ISSUE THREAD

**Issue by wugui2020** [golastmile/rasa_nlu#71]
On
https://github.com/golastmile/rasa_nlu/blob/master/src/trainers/mitie_trainer.py#L40
The increment by one on the end index is not correct. text[start:end] should get the word properly by itself. increase it by one will cause problem when a word is followed by any symbols. This bug is hidden because the next character for most words or tokens is a white space.

**Comment by amn41** [comment]
thanks! you are totally right. Referenced in PR #73
