### ISSUE TITLE
Rasa.ai added value 

### ISSUE THREAD

**Issue by Koshak118** [golastmile/rasa_nlu#79]
Hey,

Rasa.ai looks like a very interesting framework and seems to address main weak point of the current hosted NLP API solutions

We've been working for a while with scapy which makes a good work for us till now.
Should we consider switching to rasa.ai and for what reasons? I mean it seems like your framework uses scapy a lot, for example your tokenizer uses scapy's one (or mitie's)  so what are use cases you aimed to simplify/enhance and how your framework does it better than the backend libraries it wraps?

**Comment by amn41** [comment]
Hi, thanks for your interest in rasa NLU! 

GitHub issues are where we discuss bugs, implementation details, and feature requests. Your question would be more suited to Hacker News, https://news.ycombinator.com/item?id=13205039
