### ISSUE TITLE
Example of Using RASA as a Library

### ISSUE THREAD

**Issue by Reubend** [golastmile/rasa_nlu#80]
In the project's description, it says that

> rasa NLU is written in Python, but it you can use it from any language through a HTTP API. If your project is written in Python you can simply import the relevant classes.

The documentation gives an [example](http://rasa-nlu.readthedocs.io/en/latest/#the-quickest-quickstart-in-the-west) of how one would use RASA as a server, but there are no examples of how one would use RASA as a library directly in Python. 

Could you add a basic example of model training and usage from Python?

**Comment by amn41** [comment]
yes, definitely! will add soon
