### ISSUE TITLE
Wrong language is used by spacy interpreter

### ISSUE THREAD

**Issue by patrickzimmermann101** [golastmile/rasa_nlu#82]
Although language is set to "de" in described model (metadata.json) the interpreter still using "en" as default language. 

I have fixed that by overwriting the language_name in SpacySklearnInterpreter if "language" in metadata exists.

**Comment by amn41** [comment]
thanks for finding the bug and creating this issue! one workaround it to manually rename the `"language"` field to `"language_name"` in your metadata file. 

With this PR models trained in the future will have that set correctly.
