### ISSUE TITLE
[Question] Deploying to Heroku

### ISSUE THREAD

**Issue by jason-riddle** [golastmile/rasa_nlu#90]
There probably needs to be more documentation on how to deploy to heroku. I've added a deploy button in https://github.com/golastmile/rasa_nlu/pull/89 and upon attempting to deploy, I now have to or have the option to fill in the following.

- RASA_TOKEN (token for validating requests)
  - This is automatically generated, but what is this used for? Do I need to look up this value later?
- RASA_BACKEND (which backend to use)
  - Looks like this is documented here: https://github.com/golastmile/rasa_nlu/blob/master/docs/config.rst might be helpful to link back to this.
- RASA_PATH (where to save models)
  - Am I generating these models? Do I need to back these up?
- RASA_LOGDIR (where to save logs)
  - Fine as is. Could talk more about what is being logged.
- RASA_MITIE_FILE (file containing mitie feature extractor)
  - If I'm using `spacy_sklearn` for my backend, why is this still required?
- RASA_SERVER_MODEL_DIR (dir containing model which should be used to process requests)
  - Not sure what this is used for? https://github.com/golastmile/rasa_nlu/blob/master/docs/config.rst is scarse on details.
- AWS_SECRET_ACCESS_KEY (secret key for S3 access)
  - What permissions are required for uploading? Just `PutObject` or something else?
- AWS_ACCESS_KEY_ID (key id for S3 access)
  - What permissions are required for uploading? Just `PutObject` or something else?
- BUCKET_NAME (name of s3 bucket)
  - Is there a specific directory structure for the s3 bucket?
- AWS_REGION (aws region of S3 bucket)
  - Fine as is.

There probably should be another document such as `deploying-to-heroku.md` or `deploy/heroku.md` explaining what each variable does.

**Comment by amn41** [comment]
Hi Jason,

The reason we retired the 'deploy to heroku' button is because rasa won't run on the 'free' tier dynos from Heroku because they don't have enough memory. Happy to write something explaining these vars, but the idea was to let people test rasa NLU without installing a backend. Unfortunately that doesn't work with the free heroku plan so we chose to go with docker images.

If you do get it running on heroku, let me know which dyno size worked for you! We could then include it in the docs

**Comment by jason-riddle** [comment]
Ah gotcha. If it's deprecated then I'll go ahead and close https://github.com/golastmile/rasa_nlu/pull/89. Closing this issue.

**Comment by BeamerCola** [comment]
@amn41 this is great to know that it's still possible.  We're looking to deploy on heroku, we're running on very large dynos so imagine it won't be a problem.  Are there any old docs on deploying with heroku so I can give it a whirl?  

Happy to help document any setup.

**Comment by tmbo** [comment]
@BeamerCola you can have at look at the `app.json` https://github.com/golastmile/rasa_nlu/blob/master/app.json

Unfortunately, there is no other documentation. Maybe @amn41 can share some insights he had with setting it up on heroku.

**Comment by alvin-reyes** [comment]
Hi everyone. What dyno do we need to get RASA up and running? I tried deploying RASA in a free tier and it seems to work as expected.

**Comment by BeamerCola** [comment]
@alvin-reyes oh awesome.  could you share how you set it up?

**Comment by madimov** [comment]
@alvin-reyes any chance you still share your setup?
