### ISSUE TITLE
[Question] How to keep track of conversation state?

### ISSUE THREAD

**Issue by jason-riddle** [golastmile/rasa_nlu#93]
This is probably out-of-scope for this project, but is there any way to keep track of a conversation state?

**Comment by amn41** [comment]
Yes it's out with the scope of rasa NLU, but email me & I'll give you some input
![image](https://cloud.githubusercontent.com/assets/5114084/21741065/529469ac-d4c3-11e6-8a7f-edacf6981b90.png)
